phel-lang/phel-lang

src/php/Runtime.php

Improvements applied to the `Phel\Runtime` class:
* Fixed the typo
* from: "cacheDiretory" (the "c" of the "Dire**c**tory" word is missing!)
* to: "cacheDirectory"
* Applying `strict_types`
* Remove unnecesary "elses"

Refactoring the Runtime class

---

src/php/Analyzer.php

* Making the class [strict](https://github.com/Chemaclass/php-best-practices/blob/master/technical-skills/strict-types.md)
* Making the class [final](https://medium.com/@chemaclass/final-classes-in-php-9174e3e2747e)
* Using [strict comparations](https://github.com/Chemaclass/php-best-practices/blob/master/technical-skills/performance-tips.md): `===` instead of `==`
* Removing unnecessary `else` statements due to return early (really good job there!)
* It also decreases the indentation of the blocks which helps a lot to follow the logic
* Change from `protected $phpKeywords` to `private const PHP_KEYWORDS` you might guess why :)

Cleaning Analyzer class

---

src/php/Exceptions/HtmlExceptionPrinter.php
src/php/Exceptions/TextExceptionPrinter.php
src/php/Lang/PhelArray.php
src/php/Lang/Table.php
src/php/Lang/Tuple.php
src/php/Repl.php

Using null coalescing operator `$foo ?? $bar` instead of `isset($foo) ? $foo : $bar`
[Modern PHP: know the best PHP features up to PHP 7.4](https://medium.com/@chemaclass/modern-php-know-the-best-php-features-til-php-7-4-e3b2bf5916b2)

Using null coalescing operator

---

doc/content/documentation/api.md
doc/content/documentation/array-table-and-struct.md
doc/content/documentation/control-flow.md
doc/content/documentation/functions-and-recursion.md
doc/content/documentation/getting-started.md
doc/content/documentation/php-interop.md
doc/sass/_base.scss
doc/sass/_code.scss
doc/sass/_layout.scss
doc/syntaxes/phel.sublime-syntax
doc/templates/404.html
src/phel/core.phel
src/php/Analyzer.php
tests/phel/test/core.phel
tests/php/Fixtures/Let/let-binding.test
tests/php/Fixtures/Let/loop-destructure.test
tests/php/Fixtures/Let/loop.test
tests/php/Fixtures/Recur/recur-fn-one-arg.test
tests/php/Fixtures/Recur/recur-fn-two-args.test
tests/php/Fixtures/Try/try-catch-finally-expr-throw.test
tests/php/Fixtures/Try/try-catch-finally-expr.test
tests/php/Fixtures/Try/try-catch-finally.test

Some developers (me for instance) have a their editor configured to automatically remove trailing spaces. This PR should improve developer experience and PR readability when using this kind of configuration.

remove trailing spaces

---

.github/workflows/ci.yml
.gitignore
Readme.md
composer.json
devops/dev/php.dockerfile
docker-compose.yml
phpunit.xml.dist

* Adding docker-compose with docker using `PHP:7.4` for dev env
* Renamed the script names for the tests:
* `phpunit` to `test-compiler`
* `test` to `test-core`
* Added `composer psalm` and `composer csfix` to "composer scripts"
* Ignore `.idea/` directory (from PHPStorm)

Adding docker using PHP:7.4

---

build/php.dockerfile

In order to improve performances when running `composer install`, I installed zip to allow composer to use _dist_ instead of _sources_.

install zip in dockerfile

---

src/php/Lang/Struct.php
src/php/Lang/Table.php

* Declaring [strict types](https://github.com/Chemaclass/php-best-practices/blob/master/technical-skills/strict-types.md).
* Defining type properties.
* Adding return types to functions. 
* Strict conditions when possible.
* The only one case when it's not possible to define as strict condition is in the `Table::equals($other)` method.
* Removing unnecessary `else` statements due to return early.
* It also decreases the indentation of the blocks which helps a lot to follow the logic.
* No logic was altered.

Cleaning Table and Struct classes

---

build/php.dockerfile

When you try to install the project from Docker, for any reason, when it starts with the dependencies'  installation (`apt install -y git zip`), the process is cancelled.
I try some scenarios and for some strange reason if you remove the `RUN` keywords and replaced them by `&&`. With the proposal PR, it works like a charm.
1. `docker-compose up`

Fix Dockerfile dependencies

---

src/php/Analyzer.php
src/php/GlobalEnvironment.php
src/php/Runtime.php

* Making the class strict & final
* Rename the method `addDefintion()` to `addDefinition()`.
* Define the type and make properties private (better encapsulation).
* Simplify an `isset()` _L45_
* It is not necessary to check twice if the key and sub-key exists. [DEMO](http://sandbox.onlinephpfunctions.com/code/11557f70adf59254dde4705685dc6275f067de2d)
* Removing unnecessary `else` statements.
* Split the logic from `addRequireAlias()` into `resolveWithAlias()` & `resolveWithoutAlias()`.
* No logic was altered.

Cleaning GlobalEnvironment class

---

doc/content/documentation/api.md
src/phel/core.phel

I just realize that there a typo in the `keyword?` api documentation.
- I changed `string` to `keyword` for the docu related with the `keyword?`

Fix keyword? docu

---

doc/content/_index.md
doc/content/blog/functional-programming-in-php.md
doc/content/documentation/api.md
doc/content/documentation/array-table-and-struct.md
doc/content/documentation/basic-types.md
doc/content/documentation/control-flow.md
doc/content/documentation/functions-and-recursion.md
doc/content/documentation/getting-started.md
doc/content/documentation/global-and-local-bindings.md
doc/content/documentation/http-request-and-response.md
doc/content/documentation/macros.md
doc/content/documentation/namespaces.md
doc/content/documentation/numbers-and-arithmetic.md
doc/content/documentation/php-interop.md
doc/content/documentation/truth-and-boolean-operations.md
doc/content/documentation/tuple.md
src/phel/core.phel
tests/php/Fixtures/Ns/munge-ns.test

Fix typo errors from the documentation.
- Replace `can not` by `cannot` in several places.
- Replace some `a` by `an` when the next word starts by vocal.
- Fix typo words such as `programm` or `offical` by `program` or `official` and so on.
- Add a final dot at the end of each phrase in `documentation/api.md` file.
- Replace `(__DIR__ )` by `(__DIR__)` in `api.md` (line 99).
- Add a comma after `Otherwise` adverb.
- Fix some agreement errors (sing + plural).
- Update `phel/core.phel` file with `api` fixes..
- Minor changes.
Edit: Once it is merged, we can close the issue #49

Improve documentation

---

src/php/Compiler.php
src/php/Lexer.php
src/php/Quasiquote.php
src/php/Reader.php
src/php/Runtime.php
src/php/Token.php
tests/php/LexerTest.php

I refactored some classes related to the Reader and Compiler without altering its functionality.
- Declared classes as [strict](https://github.com/Chemaclass/php-best-practices/blob/master/technical-skills/strict-types.md) and [final](https://medium.com/@chemaclass/final-classes-in-php-9174e3e2747e).
- Removing unnecessary `else` statements due to return early.
- No logic was altered.
- `Quasiquote`
- I rearranged the class methods: moving the private after the public one.

Cleaning reader and compiler

---

src/php/Analyzer.php
src/php/Compiler.php
tests/php/IntegrationTest.php

I created another function in `Analyzer` in order to make more strait forward the intention of its public methods. 
```php
public function analyzeInEmptyEnv($x): Node
{
return $this->analyze($x, NodeEnvironment::empty());
}
public function analyze($x, NodeEnvironment $env): Node
{
if ($this->isLiteral($x)) {
return (new AnalyzeLiteral())($x, $env);
}
// ...
```
- The method `analyze($x, NodeEnvironment $env)` has two mandatory parameter. The `$env` is mandatory now.
- I created `analyzeInEmptyEnv($x)` which receives only one argument and "there is no env" (`NodeEnvironment::empty()`).
This way we get rid of the optional second argument and therefore the `if` condition:
```php
if (null === $env) {
$env = NodeEnvironment::empty();
}
```

Splitting analyze() in two methods

---

src/php/Analyzer/TupleSymbol/ApplySymbol.php
src/php/Analyzer/TupleSymbol/DefStructSymbol.php
src/php/Analyzer/TupleSymbol/DefSymbol.php
src/php/Analyzer/TupleSymbol/DoSymbol.php
src/php/Analyzer/TupleSymbol/FnSymbol.php
src/php/Analyzer/TupleSymbol/ForeachSymbol.php
src/php/Analyzer/TupleSymbol/IfSymbol.php
src/php/Analyzer/TupleSymbol/InvokeSymbol.php
src/php/Analyzer/TupleSymbol/LetSymbol.php
src/php/Analyzer/TupleSymbol/LoopSymbol.php
src/php/Analyzer/TupleSymbol/NsSymbol.php
src/php/Analyzer/TupleSymbol/PhpAGetSymbol.php
src/php/Analyzer/TupleSymbol/PhpAPushSymbol.php
src/php/Analyzer/TupleSymbol/PhpASetSymbol.php
src/php/Analyzer/TupleSymbol/PhpAUnsetSymbol.php
src/php/Analyzer/TupleSymbol/PhpNewSymbol.php
src/php/Analyzer/TupleSymbol/PhpObjectCallSymbol.php
src/php/Analyzer/TupleSymbol/QuoteSymbol.php
src/php/Analyzer/TupleSymbol/RecurSymbol.php
src/php/Analyzer/TupleSymbol/ThrowSymbol.php
src/php/Analyzer/TupleSymbol/TrySymbol.php
src/php/Exceptions/PhelCodeException.php
src/php/Exceptions/ReaderException.php

I refactor and clean the `Analyzer/TupleSymbol/*.php`.
- improving naming (for example: changing `$x` to `$tuple` or `$nodeEnvironment` to `$env`)
- apply extract method refactoring for almost every `else` I saw
- use named constructor (`AnalyzerException::withLocation()`) to help the creation of an `AnalyzerException`
- extract chunks of logic in private methods to keep the level of abstraction easy-peasy to understand
- no functionality was changed

Refactor TupleSymbols

---

src/phel/core.phel
src/php/Lang/Set.php
src/php/Printer.php
tests/phel/test/core.phel

This implements the set data structure described by #5. However I didn't implement the `join` function as it seems to be a duplicate of `union`.
However, I didn't update the documentation yet, I would like to get an approbation about this update first.
I tried to figure out how to parse a set with a custom notation (I was thinking about `@(1 2 3)` since this notation is not used yet and is close to another notation used in the language), but I couldn't understand what I should do exactly to get this result.
- Added tests on Sets
- Added a Set php class derived from PhelArray
- Added Set phel constructor and functions
- `(set 1 2 3 1 2 3)` create a set containing the values 1, 2 and 3 (only once since it's a set)
- `union (set 1) (set 2) (set 3)` update the values of the first set to the …

Implement Sets

---

src/phel/core.phel
tests/phel/test/core.phel

This is a bugfix to allow reduce to iterate over all values either they are `nil` or not since skipping those values should be handled by the user. Closes #80 
- Replaced the pre-recursion check on the `first` element of the sequence parameter being `nil` to a `count` of this sequence being `> 0`.
- Added tests to prevent regression.

Fixed reduce on sequences containing a nil value

---

src/php/Commands/Repl/ColorStyle.php
tests/php/Commands/Repl/ColorStyleTest.php
tests/php/Commands/Repl/ReadlineTest.php

I cannot test the methods `readHistory()`. `readline()` & `redisplay()`.
Probably I need to create some interface...
- Add `green` method in `ColorStyle`.
- Update `ColorStyleTest`.
- Create `ReadLineTest`.

Add test ColorStyle & ReadLine classes

---

src/phel/core.phel
src/php/Lang/Set.php
tests/phel/test/core.phel

`(first (set))` should return `nil` but return `false` instead. Also `second` cannot be used on a set since it uses `php/aget`.
- Added set tests
- Fixed `first` on empty set
- Updating `second` to use `first` and `next` to be compatible with sets

fix set first and second

---

tests/php/Analyzer/AnalyzeTupleTest.php

- Create `AnalyzeTupleTest` class.
- The purpose of this test is to check if the analyze factory works and depending on the input, it returns the correct class.
**PS:** I was not able to test the `default` switch case.

Add tests to AnalyzeTuple class

---

composer.json
tests/php/Analyzer/AnalyzeTupleTest.php
tests/php/Analyzer/TupleSymbol/QuoteSymbolTest.php
tests/php/Commands/Repl/ColorStyleTest.php
tests/php/Commands/Repl/ReadlineTest.php
tests/php/Commands/RunCommandTest.php
tests/php/Commands/TestCommandTest.php
tests/php/IntegrationTest.php
tests/php/Lang/TableTest.php
tests/php/LexerTest.php
tests/php/PrinterTest.php
tests/php/ReaderTest.php
tests/php/RuntimeMock.php
tests/php/RuntimeTest.php
tests/php/SourceMap/VLQTest.php

I defined `PhelTest` namespace and some other minor improvements to all unit test files.
- Moved all `test/php` tests from `Phel` to `PhelTest` namespace.
- Declared all tests as [final](https://medium.com/@chemaclass/final-classes-in-php-9174e3e2747e) and [strict](https://github.com/Chemaclass/php-best-practices/blob/master/technical-skills/strict-types.md) as well.
- Moved the "inner class" `RuntimeMock` to its own file.

Define PhelTest namespace

---

doc/content/documentation/configuration.md
doc/content/documentation/testing.md

Documentation changes to avoid beginner mistakes.
See issue #90.
- Changes `hello-world\\` in `composer.json` under key `loader-dev` to `hello-world\\tests\\` (Configuration).
- Appends `tests` to namespace in testing documentation.

Sets correct namespace for loader-dev and tests.

---

src/php/Analyzer/TupleSymbol/PhpObjectCallSymbol.php
tests/php/Analyzer/TupleSymbol/PhpObjectCallSymbolTest.php

1. We checked on line 26: `if (count($tuple) !== 3)`, so, it is not possible to reach the condition on line 59.
2. We checked on line 30: if `$tuple[2]` instance of `Tuple` or `Symbol`, and on line 39 we check if `$tuple[2]` is `Tuple`, so, the else branch is possible only when the object is a `Tuple` object (and vice versa), for that reason, conditions on lines 63 & 84 are also not necessary.
At this point I have some questions, would be possible this class could be extended making those guard clauses necessaries in the future?
I mean, what do you think is better, that "repeating" code but not having 100% but probably more secure or and have the 100%  covered without those clauses as I did in the PR? @jenshaase  
- Remove some impossible guard clauses from `PhpObjectCallSymbol` class
- …

Add tests to PhpObjectCallSymbol class

---

src/php/Analyzer/TupleSymbol/RecurSymbol.php
src/php/Ast/RecurNode.php
src/php/Emitter.php
src/php/NodeEnvironment.php
src/php/RecurFrame.php

I just clean up a little bit the `RecurSymbol` and `NodeEnvironment` classes
- Refactor a little bit the `RecurSymbol` and `NodeEnvironment` classes
- Renamed `exprs` to `expressions`
- No functionality was altered

Refactoring RecurSymbol and NodeEnvironment

---

.php_cs.dist
src/php/Destructure.php
src/php/Printer.php
src/php/ReaderResult.php

Added the no_unused_imports rule to the PHP Code Syle fixer
- Added `no_unused_imports` to the `php_cs.dist`
- Applied the fixer

Added no_unused_imports to php_cs

---

doc/content/documentation/destructuring.md

Update a wrong result on `destructuring` documentation.

Small typo on documentation

---

src/php/Lang/AbstractType.php
src/php/Lang/ICdr.php
src/php/Lang/IConcat.php
src/php/Lang/ICons.php
src/php/Lang/IFirst.php
src/php/Lang/IFn.php
src/php/Lang/IIdentical.php
src/php/Lang/IMeta.php
src/php/Lang/IPop.php
src/php/Lang/IPush.php
src/php/Lang/IRemove.php
src/php/Lang/IRest.php
src/php/Lang/ISeq.php
src/php/Lang/ISlice.php
src/php/Lang/ISourceLocation.php
src/php/Lang/Keyword.php
src/php/Lang/PhelArray.php
src/php/Lang/Set.php
src/php/Lang/SourceLocation.php
src/php/Lang/Struct.php
src/php/Lang/Symbol.php
src/php/Lang/TSourceLocation.php
src/php/Lang/Table.php
src/php/Lang/Truthy.php
src/php/Lang/Tuple.php

Small changes on `src/php/Lang/*`.
- Add `declare(strict_types=1)` to some classes.
- Remove the comment tag `@return` when it is explicitly in the code.
- Fix small typos like `$offest` to `$offset` or some return values from some methods.
- `Lang/Keyword` replace `if` clause by a coalesce operator.
- Split imports when the line is too long ([PSR-12](https://www.php-fig.org/psr/psr-12/#41-extends-and-implements)).
- Replace the call to the class itself by `self::` keyboard.
- Other minor changes.
I have updated some PhpDocs with a final dot when it was a comment but without it when it was a `@param` tag.
Looking at the `php cs fixer` I found this rule: [`phpdoc_annotation_without_dot`](https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_annotation_without_dot). …

Refactor Lang folder

---

src/php/Analyzer/TupleSymbol/FnSymbol.php
src/php/Analyzer/TupleSymbol/ReadModel/FnSymbolTuple.php

I realized that I could refactor the `FnSymbol` class again, following the same principle as I did last time with `ForeachSymbol`.
The `FnSymbolTuple` can be created using the named constructor `createWithTuple()`.
- Extracted some logic from `FnSymbol` to `FnSymbolTuple` in order to improve the readability and abstraction level of those classes.

Refactoring FnSymbol again 

---

phel
src/php/Commands/TestCommand.php
src/php/Main.php

Getting rid of the `exit` keyword in Main.
- Removed exit's from `Main`. Using an `Exception` instead.
- Clean up `TestCommand`.

Throw an Exception instead of using exit

---

src/php/Analyzer.php
src/php/Analyzer/AnalyzeLiteral.php
src/php/Analyzer/TupleSymbol/ApplySymbol.php
src/php/Analyzer/TupleSymbol/DefSymbol.php
src/php/Analyzer/TupleSymbol/InvokeSymbol.php
src/php/Ast/LiteralNode.php
src/php/Ast/QuoteNode.php
src/php/Destructure.php
src/php/Emitter/OutputEmitter.php
src/php/Emitter/OutputEmitter/LiteralEmitter.php
src/php/Lang/Keyword.php
src/php/Lang/Struct.php
src/php/Lang/Tuple.php
src/php/Quasiquote.php
src/php/Reader.php
src/php/ReaderResult.php
tests/php/Unit/ReaderTest.php

Replace `scalar` keyword from Phpdocs by the scalar types `(string|float|int|bool)`.
Check this [issue](https://github.com/jenshaase/phel-lang/issues/119) for more information 🐘

Replace scalar type by the scalar ones

---

composer.json
composer.lock
doc/build-api-page.php
doc/content/documentation/configuration.md
src/phel/test.phel
src/php/Command/CommandFactory.php
src/php/Command/CommandFactoryInterface.php
src/php/Command/RunCommand.php
src/php/Command/TestCommand.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
src/php/Compiler/Emitter/OutputEmitter/SourceMap/VLQ.php
src/php/Main.php
src/php/Runtime/Runtime.php
src/php/Runtime/RuntimeFactory.php
src/php/Runtime/RuntimeInterface.php
tests/php/Integration/Command/RunCommandTest.php
tests/php/Integration/Command/TestCommandTest.php
tests/php/Integration/Fixtures/Def/namespace-def.test
tests/php/Integration/Fixtures/Let/loop-destructure.test
tests/php/Integration/Fixtures/New/new-from-alias.test
tests/php/Integration/Fixtures/Ns/munge-ns.test
tests/php/Integration/Fixtures/Ns/require.test
tests/php/Integration/Fixtures/Ns/use.test
tests/php/Integration/IntegrationTest.php
tests/php/Unit/Runtime/RuntimeMock.php
tests/php/Unit/Runtime/RuntimeTest.php

Issue: https://github.com/jenshaase/phel-composer-plugin/issues/2
In order to decouple the Runtime creation from its logic, I created a new module named Runtime, in which you can find its Factory, the Runtime interface, and the Runtime logic.
- Created a Runtime Module with
- RuntimeFactory <- it creates/initialize the Runtime Singleton
- Runtime <- it contains the Runtime logic
- RuntimeInterface <- to invert the Runtime dependencies
- Updated the docu, tests, and namespaces in order to use the `RuntimeFactory` instead of the `Runtime` itself
In order to QA these changes, I changed the `phel/phel-composer-plugin` version branch to the latest one that is using the `RuntimeFactory` as well. Therefore, we need to:
1st) merge the other PR …

Creating runtime module

---

src/phel/http.phel

When sending a POST request with form data, `(get (http/request-from-globals) :parsed-body)` would always return `nil`.
- Fixes typo `:conent-type` to `:content-type`. 
Note: Unable to write a test for this without changing phel/http library.
@jenshaase I have managed to write a test for this, but I had to make a small change to `request-from-globals`. I will create a new PR for that change.

Bug: Fixes typo in post-global-valid

---

src/phel/http.phel
tests/phel/test/http.phel

It adds a test for issue fixed in this PR #135.
- Adds test for post with form data. 
- Adds `post` parameter to `request-from-globals` in order to be able to test it. @jenshaase This seemed like the fastest way of doing this. We could add a method like `get-post-from-globals` like we have `get-method-from-globals`, but this seemed simpler. Open for suggestions.

Adds test for post with form data.

---

composer.json
composer.lock

Sometimes is really useful to have the "**var-dumper Symfony Component**" to be able to "dump" some values during run time for debugging purposes. This dependency provides you with two really nice functions:
- `dump(...$var)`: it nicely dumps anything (in a beautiful format, actually!)
- `dd(...$var)`: it dumps and dies, similar to the previous dump 😄 
The fact that it's a **require-dev** dependency shouldn't affect the prod run time for the final consumer/client.
- Adding `symfony/var-dumper` as **require-dev** dependency

Adding var-dumper as require-dev dependency

---

doc/content/documentation/api.md
src/phel/core.phel
tests/phel/test/core.phel

I was thinking about to implement something like the new [`str_contains`](https://www.php.net/manual/en/function.str-contains) (able in PHP 8). So I did.
- Added the `str-contains?` function in phel with some unit tests
- Updated the API docu using `php doc/build-api-page.php > doc/content/documentation/api.md`

Implement str-contains? in phel

---

doc/content/documentation/array-table-and-struct.md

I think that this is a typo.
Fixes typo in documentation for Array, Table, Struct and Set.
- Changes `my_struct` to `my-struct`.

Fixes typo.

---

doc/content/documentation/api.md
src/phel/core.phel

🍨 Issue: https://github.com/jenshaase/phel-lang/issues/161 
Be able to use [$argv](https://www.php.net/manual/en/reserved.variables.argv.php) from phel 
- Added `argv` as constant in `core.phel`.
As a follow-up idea we could develop a library to parse key-value arguments. Something like
```bash
php phel run src/phel/local.phel k1=v1 k2=v2
```
And (parse-key-values argv), as simple example:
```
array:5 [
0 => "phel"
1 => "run"
2 => "src/phel/local.phel"
'k1' => "v1"
'k2' => "v2"
]
```

Adding argv to the core

---

src/php/Command/Shared/NamespaceExtractor.php

I noticed [PHP Extensions (EA Extended)](https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-) plugin was notifying it's not recommended to use `array_merge` function inside loops.
If you think, it makes sense, you are overriding the same array with the same data plus the new value over and over for each loop iteration.
- [Never Use array_merge in a Loop | Chemaclass](https://medium.com/swlh/never-use-array-merge-in-a-loop-74917b056ff9)

Remove array_merge from loop

---

doc/content/documentation/api.md
src/phel/core.phel
tests/phel/test/core.phel

Added some more `Phel` functions to the core.
- Added `format`: Returns a string produced according to the formatting string fmt.
- Added `printf`: Output a formatted string.

Added format + printf phel functions

---

composer.json
composer.lock

Installing for dev purposes this tool https://github.com/phpmetrics/phpmetrics, which provides a lot of nice metrics for the project. You can see what metrics you can find here https://github.com/phpmetrics/PhpMetrics/blob/master/doc/metrics.md
- Added latest version of `phpmetrics/phpmetrics` to `require-dev`
- Added a composer script alias `composer metrics-report` which runs: 
- `./vendor/bin/phpmetrics --report-html=data/metrics-report src/php`
Because it's a `require-dev` it won't have any impact on the users of `phel` when downloading as a dependency itself.

Installing phpmetrics in require-dev

---

composer.json

`infection` was not "enabled" in the composer scripts because it was not working.
The problem was I/we missed to add the `XDEBUG_MODE=coverage` flag to make it works. With the flag, `infection` works like a charm.
[Here is the issue](https://github.com/infection/infection/issues/1473#event-4233608893) I opened in the infection project about how to solve this problem. 😃

Add infection to composer

---

phel
src/php/Command/ReplCommand.php
src/php/Exceptions/HtmlExceptionPrinter.php
src/php/Exceptions/TextExceptionPrinter.php

https://github.com/jenshaase/phel-lang/issues/187 Prevent REPL from being closed on Exception
- Add a global try-catch block in the REPL loop to ensure it won't be close by any error. Instead, it will output the error message.
- Fix the ExceptionPrinters; the `$frame['args']` aren't present always, so using the `?? []` would be sufficient to avoid triggering a new error while rendering the actual "current error" ;)
Before this was exiting the REPL:
```clojure
(print (\readline_info "library_version"))
```
With this PR it doesn't exit the REPL anymore.

Fix errors from the printers + catch potential error in repl

---

src/phel/repl.phel
src/phel/test.phel
src/php/Command/CommandFactory.php
src/php/Command/Repl/startup.phel
src/php/Compiler/CompilerFactory.php
src/php/Compiler/Emitter/OutputEmitter.php
src/php/Compiler/Emitter/OutputEmitter/LiteralEmitter.php
src/php/Printer/Printer.php
src/php/Printer/TypePrinter/BooleanPrinter.php
src/php/Printer/TypePrinter/KeywordPrinter.php
src/php/Printer/TypePrinter/NullPrinter.php
src/php/Printer/TypePrinter/NumberPrinter.php
src/php/Printer/TypePrinter/PhelArrayPrinter.php
src/php/Printer/TypePrinter/SetPrinter.php
src/php/Printer/TypePrinter/StringPrinter.php
src/php/Printer/TypePrinter/StructPrinter.php
src/php/Printer/TypePrinter/SymbolPrinter.php
src/php/Printer/TypePrinter/TablePrinter.php
src/php/Printer/TypePrinter/TuplePrinter.php

Issue: https://github.com/phel-lang/phel-lang/issues/197
Pass a printer with colors to the REPL printer, so it can handle the colors for each individual type printer.
- Add colors to REPL printer
- By default, all TypePrinters are without color
- Added `print-colorful` to `core/repl.phel`, because `println` wont render any color.
When using `(print ...)` function doesn't render the colors because print uses print-str, and there we are using a nonReadable printer without colors:  ```printer (php/:: Printer (nonReadable))```. The problem here is that `print-str`  is the "same as print. But instead of writing it to an output stream. The resulting string is returned."
```clojure
(defn print-str
"Same as print. But instead of writing it to an output stream,
The resulting string is returned." …
```

Basic colors to repl printers

---

src/php/Printer/Printer.php
src/php/Printer/TypePrinter/AnonymousClassPrinter.php
src/php/Printer/TypePrinter/ArrayPrinter.php
src/php/Printer/TypePrinter/BooleanPrinter.php
src/php/Printer/TypePrinter/KeywordPrinter.php
src/php/Printer/TypePrinter/NonPrintableClassPrinter.php
src/php/Printer/TypePrinter/NumberPrinter.php
src/php/Printer/TypePrinter/SymbolPrinter.php
src/php/Printer/TypePrinter/ToStringPrinter.php
src/php/Printer/TypePrinter/WithColorTrait.php
tests/php/Unit/Printer/PrinterTest.php
tests/php/Unit/Printer/TypePrinter/AnonymousClassPrinterTest.php
tests/php/Unit/Printer/TypePrinter/ArrayPrinterTest.php
tests/php/Unit/Printer/TypePrinter/NonPrintableClassPrinterTest.php
tests/php/Unit/Printer/TypePrinter/ToStringPrinterTest.php

Issue: https://github.com/phel-lang/phel-lang/issues/204
In order to avoid exceptions when printing anything from the REPL, I created 3 new printers.
- Created `WithColorTrait` for the Printers.
- Print one level of data from the `ArrayPrinter` instead of displaying only `<PHP-Array>`. 
- Created new printers:
- `ToStringPrinter`: it calls the `__toString()` in case the object has it.
- `AnonymousClassPrinter`: it notifies you that that class is an anon class, that's all.
- `NonPrintableClassPrinter`: it tells you that the class that you are trying to print is not printable.

Fix repl cannot print all values

---

doc/content/documentation/functions-and-recursion.md

Change `This can be done by applied the` to `This can be done by applying the`
Probably a nitpick, but found this typo while first reading through the docs.
See above.

Fix typo in functions-and-recursion docs

---

src/php/Command/ReplCommand.php

Closes https://github.com/phel-lang/phel-lang/issues/205
When you press `<ENTER>` in the REPL, even if the statement is incorrect, it will be saved inside the `phel-repl-history` file.

Save in history incorrect REPL expressions

---

src/php/Command/CommandFacade.php
src/php/Command/CommandFacadeInterface.php
src/php/Command/CommandFactory.php
src/php/Command/FormatCommand.php
src/php/Command/Shared/CommandIoInterface.php
src/php/Command/Shared/CommandSystemIo.php
src/php/Compiler/Parser/Parser.php
src/php/Compiler/Parser/ParserInterface.php
src/php/Formatter/Formatter.php
src/php/Formatter/FormatterInterface.php
tests/php/Integration/Command/FormatCommandTest.php

Issue: https://github.com/phel-lang/phel-lang/issues/216
When running the "phel fmt" command, in case the phel file has any parsing error we didn't show much feedback.
- Include the ExceptionPrinter to the FormatCommand, so in case the formatted encounters any error, it will render the file and exact location where the error was found.
Here you can see an example of the output when the phel code is malformed (I added the `]` for testing purpose):

Use ExceptionPrinter in FormatCommand

---

src/php/Compiler/Analyzer/Analyzer.php
src/php/Compiler/Analyzer/AnalyzerInterface.php
src/php/Compiler/Emitter/Emitter.php
src/php/Compiler/Emitter/EmitterInterface.php
src/php/Compiler/Emitter/EvalEmitter.php
src/php/Compiler/Emitter/EvalEmitterInterface.php
src/php/Compiler/EvalCompiler.php
src/php/Compiler/FileCompiler.php
src/php/Compiler/FileCompilerInterface.php
src/php/Compiler/Reader/ReaderInterface.php
src/php/Exceptions/CompiledCodeIsMalformedException.php
src/php/Exceptions/FileException.php
src/php/Runtime/Runtime.php

It helps us to recognize the potential Exceptions that you can encounter in those specific contexts.
- Created `CompiledCodeIsMalformedException` & `FileException` that will be triggered from the `EvalEmitter` instead of the native `\RuntimeException`
- Added `@throws Exceptions...` in PHPDoc for the EvalEmitter context

Improve exceptions triggered from EvalEmitter

---

.php_cs.dist
src/php/Compiler/Lexer/TokenStream.php
tests/php/Unit/Compiler/Analyzer/TupleSymbol/DefSymbolTest.php
tests/php/Unit/Compiler/Analyzer/TupleSymbol/InvokeSymbolTest.php
tests/php/Unit/Compiler/Analyzer/TupleSymbol/LoopSymbolTest.php
tests/php/Unit/Compiler/Reader/ReaderTest.php
tests/php/Unit/Lang/SetTest.php
tests/php/Unit/Lang/SourceLocationTest.php
tests/php/Unit/Lang/SymbolTest.php
tests/php/Unit/Lang/TruthyTest.php

I saw a lot of methods that don't have the `void` return.
- Add the rule (`'void_return' => true`) to the `.php_cs.dist` file
- Execute the command `composer csfix` and check tests are green 🍏

Add rule void_return to php_cs

---

src/php/Command/CommandFacade.php
src/php/Command/CommandFacadeInterface.php
src/php/Command/Export/ExportCommand.php
src/php/Command/Export/FunctionsToExportFinderInterface.php
src/php/Command/Format/FormatCommand.php
src/php/Command/Shared/NamespaceExtractor.php
src/php/Compiler/EvalCompiler.php
src/php/Compiler/FileCompiler.php
src/php/Compiler/Lexer/Exceptions/LexerValueException.php
src/php/Compiler/Lexer/Lexer.php
src/php/Compiler/Lexer/LexerInterface.php
src/php/Formatter/AbstractZipper.php
src/php/Formatter/Exceptions/ZipperException.php
src/php/Formatter/Formatter.php
src/php/Formatter/FormatterInterface.php
src/php/Formatter/ParseTreeZipper.php
src/php/Formatter/Rules/RemoveSurroundingWhitespaceRule.php
src/php/Formatter/Rules/RuleInterface.php
src/php/PhelFacade.php
tests/php/Unit/Formatter/ZipperTest.php

Minor clean up to make the exception more explicit.
- Adding `@throws` PHPDoc blocks when necessary.
- Adding some name constructor exceptions to make them more domain specific.

Minor exceptions clean-up

---

src/php/Command/CommandFacade.php
src/php/Command/CommandFacadeInterface.php
src/php/Command/CommandFactory.php
src/php/Command/Export/ExportCommand.php
src/php/Command/Format/FormatCommand.php
src/php/Command/Repl/ReplCommand.php
src/php/Command/Repl/ReplCommandIoInterface.php
src/php/Command/Repl/ReplCommandSystemIo.php
src/php/Command/Run/RunCommand.php
src/php/Command/Shared/CommandIoInterface.php
src/php/Command/Shared/CommandSystemIo.php
src/php/Command/Test/Exceptions/CannotFindAnyTestsException.php
src/php/Command/Test/TestCommand.php
src/php/Compiler/Exceptions/CompilerException.php
src/php/PhelFacade.php
tests/php/Integration/Command/Repl/ReplCommandTest.php
tests/php/Integration/Command/Repl/ReplTestIo.php
tests/php/Integration/Command/Run/RunCommandTest.php
tests/php/Integration/Command/Test/TestCommandTest.php

Don't throw up the logic exceptions from the commands, but handle them inside the commands themselves.
- Remove the `@throws ...` from the commands. They don't intentionally throw an exception up.
- Catch and handle the exceptions inside the `command->run()` logic.

Handle exceptions inside commands

---

src/php/Command/Run/RunCommand.php
tests/php/Integration/Command/Test/TestCommandTest.php

Minor additions that I forgot while doing "Handle exceptions inside commands" https://github.com/phel-lang/phel-lang/pull/236
- Added `CompilerException` catch in `RunCommand`
- Added missing assertions to `TestCommandTest`

Add missig catch in run command

---

doc/content/documentation/configuration.md
doc/content/documentation/php-interop.md

Fix some broken links on documentation:
1. [PHP-Interop (Using the export command)](https://phel-lang.org/documentation/php-interop/#using-the-export-command) ⇨ _Configuration_
2. [Configuration (Export)](https://phel-lang.org/documentation/configuration/#export) ⇨ _PHP Interop_

Fix some links on Documentation

---

Readme.md
tools/git-hooks/init.sh
tools/git-hooks/pre-commit.sh

- Added `composer test-all` to the git "pre-commit" hook. 
This is optional, but I find it really useful as I run manually this command every time before I commit something. 
The whole check takes around 10 sec and ensures that every commit is fine with the CI.
I wrote in the `README` a command to easily enable this feature: `./tools/git-hooks/init.sh`

Adding git pre-commit hook

---

src/php/Command/Format/FormatCommand.php
src/php/PhelFacade.php

Rename `fmt` to `format`:
```bash
➜  phel-lang git:(feature/rename-fmt-command) ./phel
Usage: phel [command]
Commands:
repl
Start a Repl.
run <filename-or-namespace>
Runs a script.
test <filename> <filename> ...
Tests the given files. If no filenames are provided all tests in the
"tests" directory are executed.
format <filename-or-directory> ...
Formats the given files.
export
Export all definitions with the meta data `@{:export true}` as PHP classes.
By default, it will search in the `src/` directory. All configuration
options need to be set in composer.json.
help
Show this help message.
```

Rename fmt to format

---

composer.json
composer.lock

The version of psalm 4.6.4 is breaking our type checker CI, there must be some incompatibilities, so I would rather lock the version of psalm to the previous latest one 4.6.3 in order to have a green CI. And we'll try to upgrade psalm in another future version.
- Lock psalm to 4.6.3
- Updated all other composer dev dependencies
This PR fixes the CI on this one: https://github.com/phel-lang/phel-lang/pull/244

Lock psalm to 4.6.3 and update composer

---

src/phel/core/sequence-functions.phel
src/phel/core/sequence-operation.phel
src/phel/http.phel
src/phel/repl.phel
src/php/Compiler/Analyzer/TypeAnalyzer/AnalyzeSymbol.php
src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/Binding/BindingValidator.php
src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/NsSymbol.php
src/php/Compiler/Evaluator/Exceptions/FileException.php
src/php/Compiler/Parser/ParserNode/ListNode.php
src/php/Compiler/Parser/ParserNode/QuoteNode.php
src/php/Compiler/Reader/Reader.php
src/php/Formatter/Exceptions/ZipperException.php
src/php/Formatter/Formatter/AbstractZipper.php
src/php/Lang/Collections/LinkedList/EmptyList.php
src/php/Lang/Collections/Vector/SubVector.php
src/php/Printer/Printer.php
src/php/Printer/TypePrinter/NonPrintableClassPrinter.php
src/php/Runtime/Runtime.php
tests/phel/test/http.phel
tests/php/Integration/Command/Repl/Fixtures/undefined-symbol.test
tests/php/Unit/Compiler/Analyzer/AnalyzeSymbolTest.php
tests/php/Unit/Compiler/Analyzer/SpecialForm/Binding/BindingValidatorTest.php
tests/php/Unit/Compiler/Analyzer/SpecialForm/InvokeSymbolTest.php
tests/php/Unit/Printer/TypePrinter/NonPrintableClassPrinterTest.php

Replace `can not` by `cannot` in the message errors.
This word is correct only when it's written as a single word, you can check some information in this [link](https://www.grammarly.com/blog/cannot-or-can-not/). 😄 
- No logic was altered

Replace can not by cannot

---

src/php/Compiler/CompilerFactory.php
src/php/Compiler/Emitter/Emitter.php
src/php/Compiler/Emitter/OutputEmitter.php
src/php/Compiler/Emitter/OutputEmitter/SourceMap/SourceMapState.php
src/php/Compiler/Emitter/OutputEmitterInterface.php

Refactored some methods in Emitter and OutputEmitter. The target of the Pull Request is to decouple the generation of the source map and the generation of the source code.
- OutputEmitter::emitNodeAsString was moved to Emitter
- OutputEmiitter uses now a SourceMapState object.
- OutputEmiitter has methods to reset it's state

Refactored Emitter and OutputEmitter

---

composer.json
composer.lock
src/php/Command/Run/RunCommand.php
src/php/Command/Test/TestCommand.php
tests/php/Integration/Command/Test/TestCommandTest.php

Add the total time that the "phel test" needs to complete. Similar as PHPUnit has. For example: 
```
......................................................................
Passed: 710
Failed: 0
Error: 0
Total: 710
Time: 00:21.911, Memory: 58.00 MB <------ 
```
- Require `phpunit/php-timer`, which has already this logic ready to be used 👌🏻
- Add execution time and resource usage always for `test` command and optional for `run` command.
Some examples about how it looks like now:

Add execution time and resource usage

---

src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/NsSymbol.php

Fixes #254 by disallowing any unexpected keywords in `ns`, i.e. anything besides `:use` or `:require`.
- Adds a condition to handle any keyword that isn't `:use` or `:require` by raising an exception

Disallows unexpected keywords in ns

---

src/phel/test.phel
src/php/Command/Test/TestCommand.php
src/php/Command/Test/TestCommandOptions.php
tests/php/Unit/Command/Test/TestCommandOptionsTest.php

Implementing a filter option for the test command, so you can run the tests by their name.
I applied some feedback from the other PR: https://github.com/phel-lang/phel-lang/pull/277/files
- Added: `:test-name` to the test macro
- Created `TestCommandOptions` to encapsulate all options for the `TestCommand`

Add a filter option to test command

---

src/phel/test.phel

- Extract some code from from `report` into 2 functions: `print-report-state`, `should-report-println`
- Use hash-maps instead of arrays everywhere but on the global private variable `stats`. I left `stats` as an array in order to be able to mutate its state and keep using `(update-in stats [:counts :total] inc)`. Maybe there is a better alternative, @jenshaase, in order to use a hash-map in this context as well?

Refactoring test.phel

---

src/php/Command/CommandDependencyProvider.php
src/php/Command/CommandFactory.php
src/php/Command/Run/RunCommand.php
src/php/Command/Test/TestCommand.php
src/php/Compiler/Compiler/NamespaceExtractor.php
src/php/Compiler/CompilerFacade.php
src/php/Compiler/CompilerFacadeInterface.php
src/php/Compiler/CompilerFactory.php
src/php/Interop/ExportFinder/FunctionsToExportFinder.php
src/php/Interop/InteropDependencyProvider.php
src/php/Interop/InteropFactory.php
src/php/NamespaceExtractor/NamespaceExtractorDependencyProvider.php
src/php/NamespaceExtractor/NamespaceExtractorFacade.php
src/php/NamespaceExtractor/NamespaceExtractorFacadeInterface.php
src/php/NamespaceExtractor/NamespaceExtractorFactory.php

In order to decrease the responsibilities of the Compiler module (its Facade interface shows how many things can that module do; aka its responsibilities), I would rather encapsulate these two new responsibilities in another module.
- Move `NamespaceExtractor` from Compile module to its own module

Move NamespaceExtractor from Compile module to its own module

---

src/php/Compiler/Compiler/CodeCompiler.php
src/php/Compiler/Compiler/EvalCompiler.php
src/php/Compiler/Compiler/EvalCompilerInterface.php

**CodeCompiler vs EvalCompiler**
- Does it makes sense to DRY the `EvalCompiler`?
- Can we use the `CodeCompiler` inside the `EvalCompiler` in order to avoid code duplication?
The answer is "nope". I think these two compilers have different responsibilities and they have different purposes and, actually, different logic and behavior inside. They look a bit similar (indeed; they share part of the namespace `Compiler`) but so far I wasn't able to find a way to combine them in a good way.
I like how it is for now. Maybe I will come back to this one in the future.
- Apply some minor clean-up on `CodeCompiler` & `EvalCompiler` in order to improve readability.

Minor clean-up on Code|EvalCompiler

---

src/php/Command/Test/TestCommand.php
src/php/Interop/ExportFinder/FunctionsToExportFinder.php
src/php/Interop/ExportFinder/FunctionsToExportFinderInterface.php
src/php/NamespaceExtractor/Extractor/ExtractorException.php
src/php/NamespaceExtractor/Extractor/NamespaceExtractor.php
src/php/NamespaceExtractor/Extractor/NamespaceExtractorInterface.php
src/php/NamespaceExtractor/Extractor/NamespaceInformation.php
src/php/NamespaceExtractor/NamespaceExtractorFacade.php
src/php/NamespaceExtractor/NamespaceExtractorFacadeInterface.php
src/php/NamespaceExtractor/NamespaceExtractorFactory.php

This Refactoring makes the NamespaceExtractor more independent from the compiler module.
- Return a `NamespaceInformation` object instead of the `NsNode`
- Move NamespaceExtractor classes from the compiler module to the NamespaceExtractor module.

Make NamespaceExtractor more independent

---

Changelog.md
src/phel/core.phel
tests/phel/test/core/sequence-operation.phel

Related to https://github.com/phel-lang/phel-lang/issues/305 
You are currently not able to exec push with a non-variable as 1st argument. Well, you get a really annoying NOTICE 
`(push [] 1)`. The reason was that the `push` function was using the iterable argument as a reference.
- Remove passing by reference the 1st argument in the phel `push` function.

Remove passing by ref the array to the push function

---

composer.lock

Update manually the dependencies from:
- `symfony/var-dumper` v5.3.0 to 5.3.3 [link](https://github.com/phel-lang/phel-lang/pull/314)
- `symfony/console` v5.3.0 to 5.3.2 [link](https://github.com/phel-lang/phel-lang/pull/313)
- `phpunit/phpunit` v9.5.4 to 9.5.6 [link](https://github.com/phel-lang/phel-lang/pull/312)
- `vimeo/psalm` v4.7.3 to 4.8.1 [link](https://github.com/phel-lang/phel-lang/pull/311)

Update symfony, phpunit & psalm dependencies

---

src/php/Command/Repl/InputResult.php
src/php/Command/Repl/ReplCommand.php
tests/php/Unit/Command/Repl/InputResultTest.php

If the last result from the REPL is a scalar value, you will be able to use it in your terminal by using `$_`.
- Add an `InputResult` class that is able to read the input buffer from the terminal and replace the placeholder (dollar sign + underscores)`$_` to the previous result.
Some examples using simple math operations.
As you can see, `println` function returns `nil`, so that's the latest produced value. 
Some other examples using string and bool types:
To be considered: you cannot use `$_` to use a function, only scalar values.
Edge case: avoid replacing the value inside double quotes (string)

Use `$_` to get latest result from the REPL

---

phel
src/php/Command/CommandFacade.php
tests/php/Integration/Command/AbstractCommandTest.php
tests/php/Integration/Command/Export/ExportCommandTest.php
tests/php/Integration/Command/Format/FormatCommandTest.php
tests/php/Integration/Command/Run/RunCommandTest.php
tests/php/Integration/Command/Test/TestCommandTest.php

The Command module doesn't have a Facade, so we are using the Factory directly in the `phel` script 
(and in the integration tests).
- Add CommandFacade to make clear what are the entry points from the Command module.

Create CommandFacade and use it as entry point instead of CommandFactory

---

src/phel/core.phel
tests/phel/test/core/sequence-functions.phel

All native PHP sorting functions should return an int and not a bool value.
```
usort(): Returning bool from comparison function is deprecated, 
return an integer less than, equal to, or greater than zero. 
Aka: the spaceship operator instead.
```
Source: https://wiki.php.net/rfc/stable_sorting
Therefore, currently, when running the tests from the core using PHP 8.0+ you can see this warning notice:
And this was the result of using the function `<` as a sorting function in one test -> `(sort @[3 2 1 2 3] <)`
- Add a new core function as an alias for the new PHP spaceship operator `<=>`
- Use this new function in that previous "sorting test" with that warning
- Add another function `>=<` for the inversing sorting operation like `<=>`

Add spaceship operator function

---

.github/workflows/ci.yml

We can ensure that phel is compatible with PHP 7.4 and 8 and other OS.
- Add a matrix strategy to CI tests

Add matrix OS and PHP version on CI

---

composer.json
composer.lock

Add in `composer.json`
```json
"config": {
"platform": {
"php": "7.4"
}
},
```
Now it's possible to keep with PHP 7.4 as the "official" PHP version on `Phel` BUT we can use locally a greater version like PHP 8 (which is actually like 4 times faster), in addition we won't break the CI when we run `composer update` command 😄

Add config platform php 7.4 to composer json

---

src/php/Command/Run/RunCommand.php

Before we could access the `argv` global values from PHP using the function:
```clojure
(def argv
"Array of arguments passed to script."
(php/aget php/$GLOBALS "argv"))
```
But, since we are using the Symfony console command, we don't allow using additional arguments when running phel scripts. 
- Add to the `RunCommand` one more argument as `InputArgument::IS_ARRAY` and `OPTIONAL` ([source](https://symfony.com/doc/2.3/components/console/introduction.html#using-command-arguments)).

Allow optional argv in RunCommand

---

src/php/Build/BuildDependencyProvider.php
src/php/Build/BuildFacade.php
src/php/Build/BuildFacadeInterface.php
src/php/Build/BuildFactory.php
src/php/Build/Extractor/ExtractorException.php
src/php/Build/Extractor/NamespaceExtractor.php
src/php/Build/Extractor/NamespaceExtractorInterface.php
src/php/Build/Extractor/NamespaceInformation.php
src/php/Command/CommandDependencyProvider.php
src/php/Command/CommandFactory.php
src/php/Command/Run/RunCommand.php
src/php/Command/Test/TestCommand.php
src/php/Interop/ExportFinder/FunctionsToExportFinder.php
src/php/Interop/ExportFinder/FunctionsToExportFinderInterface.php
src/php/Interop/InteropDependencyProvider.php
src/php/Interop/InteropFactory.php

I renamed the `NamespaceExtractorFacade` to `BuildFacade`. The new BuildFacade should later contain more method to build and compile a complete project. Additional work will be done in the following PRs.
- Renamed namespace Phel\NamespaceExtractor to Phel\Build
- Renamed NamespaceExtractorFacade to BuildFacade
- Renamed all other module classes accordingly.

Renamed NamespaceExtractorFacade to BuildFacade

---

src/php/Build/BuildFacadeInterface.php
src/php/Build/BuildFactory.php
src/php/Build/Extractor/NamespaceExtractor.php
src/php/Build/Extractor/NamespaceSorterInterface.php
src/php/Build/Extractor/TopologicalNamespaceSorter.php
src/php/Build/Extractor/TopologicalSorting.php
tests/php/Integration/Command/Test/Fixtures/test-cmd-project-success/test2.phel
tests/php/Unit/Build/Extractor/TopologicalSortingTest.php

The method `NamespaceExtractor::getNamespacesFromDirectories` returns now a sorted list of namespace information. They are sorted based on their dependencies. File that depend on other files will be sorted at the end and files with no dependencies will be sorted at the beginning.
This is useful for the upcoming compile command. The compile command can use this order to compile files in the correct order.

Extracted namespaces are now sorted based on their dependecies

---

src/php/Command/CommandConfig.php
src/php/Command/CommandFactory.php
src/php/Command/Repl/ReplCommand.php

Issue: https://github.com/phel-lang/phel-lang/issues/341
The REPL startup script (`startup.phel`) is loaded when any command is executed and not ONLY when the REPL command is executed.
Move the `loadFileIntoNamespace()` from the `CommandFactory` (which was being called for every command when creating all commands in the phel entry point script) to the `ReplCommand::execute()` function

Load replStartupFile on ReplCommand->execute()

---

phel-config.php
src/php/Config/ExportConfiguration.php
src/php/Config/TestConfiguration.php

Right now you can pass either a string or an array of strings. I think it is simpler to just allow `string ...$dirs` using the variadics function (native PHP). I wrote last year a post about this: [Typed arrays in PHP
](https://chemaclass.es/blog/typed-arrays-php/)
It unifies the argument to `setDirectories(string ...$directories)`. There is no need to pass an array itself when calling that method, but it will be received as an array of strings. For example:
```php
return (new ProjectConfiguration())
->setTestConfiguration((new TestConfiguration())
->setDirectories('path-1/'))
->setExportConfiguration((new ExportConfiguration())
->setDirectories('path-1/', 'path-2/', 'path-3/'));
```

Using arg unpacking in config dirs setters

---

src/php/Build/BuildFacade.php
src/php/Build/BuildFacadeInterface.php
src/php/Build/BuildFactory.php
src/php/Build/Compile/CompiledFile.php
src/php/Build/Compile/DependenciesForNamespace.php
src/php/Build/Compile/FileCompiler.php
src/php/Build/Compile/FileEvaluator.php
src/php/Build/Compile/ProjectCompiler.php
src/php/Build/Extractor/NamespaceExtractor.php

We don't want to have any logic in the Facade. The Facade should be like a "proxy" delegating all logic to domain classes that the Factory creates for it.
The main reason is that you cannot easily write tests for the Facade. Actually, you cannot write unit tests for the Facade because it is part of the infrastructure layer (like the Factory or Config, for example). That said, of course, it's always a good idea to have integration tests that test the Facade methods (at least with the happy paths), because these are the endpoints/usages of a module, from beginning to end.
For this reason, you want to have isolated classes with the logic of your domain, and using the Factory to create your domain classes injecting all collaborators/dependencies that your domain classes need. 
☝️ This way …

Refactor BuildFacade; extract to classes the logic from the facade

---

src/php/Command/Runtime/RuntimeFileGenerator.php
src/php/Runtime/Runtime.php
src/php/Runtime/RuntimeInterface.php
tests/php/Integration/Command/Export/vendor/PhelRuntime.php
tests/php/Integration/Command/Test/vendor/PhelRuntime.php
tests/php/Integration/Printer/vendor/PhelRuntime.php
tests/php/Unit/Command/Runtime/RuntimeFileGeneratorTest.php

This function removes the `Runtime::loadNs` function. It is not needed anymore.

Remove Runtime::loadNs function

---

phel-config.php
tests/phel/test/core.phel
tests/phel/test/core/basic-constructors.phel
tests/phel/test/core/basic-sequence-operation.phel
tests/phel/test/core/bitwise-operation.phel
tests/phel/test/core/boolean-operation.phel
tests/phel/test/core/control-structures.phel
tests/phel/test/core/for-loop.phel
tests/phel/test/core/function-operation.phel
tests/phel/test/core/math-operation.phel
tests/phel/test/core/more-sequence-operation.phel
tests/phel/test/core/print-operation.phel
tests/phel/test/core/regex-functions.phel
tests/phel/test/core/sequence-functions.phel
tests/phel/test/core/sequence-operation.phel
tests/phel/test/core/set-operation.phel
tests/phel/test/core/threading-macros.phel
tests/phel/test/core/type-operation.phel
tests/phel/test/html.phel
tests/phel/test/http.phel
tests/phel/test/special-forms.phel

Use phel-test as a prefix for tests/phel directory, because just "phel" is already in use for the production phel library itself.
Also, I think we can end up with some collision of naming when unifying all src and test keys when doing ns extraction per file. But anyhow, I think we get some benefits already by having diff namespaces for different contexts. And in this case, for test context, it makes totally sense.
- Change `phel\\` to `phel-test\\` the `loader-dev` phel test namespace

Use phel-test as a prefix for tests/phel directory

---

src/php/Run/Finder/ComposerVendorDirectoriesFinder.php

I discovered this bug when I was updating the phel-scaffolding repo. The "vendor/" was missing from the `pathPrefix`, and therefore the dependency was not found.
I actually don't remember why I did that `substr()` but without that, I think it makes sense. And everything seems to be working.
I think we should write an integration test for this. It will be complex due to the real files with I/O stuff (`glob()` & `require`), but I think it is worth trying this in order to avoid this bug in the future.
Anyway, I think we can postpone that as "tech debt" for the next release.

Wrong pathPrefix on ComposerVendorDirectoriesFinder

---

.gitignore
psalm.xml
src/php/Build/BuildFacadeInterface.php
src/php/Build/Extractor/NamespaceExtractor.php
src/php/Command/CommandConfig.php
src/php/Command/CommandFacade.php
src/php/Command/CommandFacadeInterface.php
src/php/Command/CommandFactory.php
src/php/Command/Domain/CodeDirectories.php
src/php/Command/Finder/ComposerVendorDirectoriesFinder.php
src/php/Command/Finder/DirectoryFinder.php
src/php/Command/Finder/DirectoryFinderInterface.php
src/php/Command/Finder/PhelFileFinder.php
src/php/Command/Finder/PhelFileFinderInterface.php
src/php/Command/Finder/VendorDirectoriesFinderInterface.php
src/php/Interop/Command/ExportCommand.php
src/php/Interop/ExportFinder/FunctionsToExportFinder.php
src/php/Interop/InteropFactory.php
src/php/Run/Command/Repl/ReplCommand.php
src/php/Run/Command/Test/TestCommand.php
src/php/Run/RunConfig.php
src/php/Run/RunFactory.php
src/php/Run/Runner/NamespaceRunner.php
tests/php/Integration/Interop/Command/Export/config/phel-config.php
tests/php/Integration/Run/Command/Repl/ReplCommandTest.php
tests/php/Integration/Run/Command/Repl/config/phel-config.php

This way we can access `src-dirs` + `vendor` dependencies from other modules (like Interop, so we can use it in the `ExportCommand` as well).
I think the `src-dirs`, `test-dirs`, and vendor would be interesting information for all general commands. For example, the `ExportCommand` (from the Interop module) needs to know about the `src-dirs` in order to compile the export code properly.
- Move the Finder folder from the `Run` to the `Command` module.
Some screenshots from the phel-scaffolding project.

Move the src Finder from the Run to the Command module

---

src/php/Build/Compile/FileCompiler.php
src/php/Compiler/Analyzer/Environment/GlobalEnvironment.php
tests/php/Integration/Build/Command/CompileCommandTest.php
tests/php/Integration/Build/Command/src/hello.phel

This adds a `*compile-mode*` variable to Phel that will be set to true if a file is compiled. This flag can be used to prevent that side effects (like `print`) are executed while running the compile command.
- Added internal `*compile-mode*` definition
- Initial value is `false`
- Set the value to `true` in the `FileCompiler` class before the `compile` function is executed.
- Reset to `false` after the `compile` function is done.

Added internal compile mode definition

---

Changelog.md
src/phel/core.phel
src/php/Lang/TypeFactory.php
src/php/Lang/Variable.php
tests/phel/test/core.phel
tests/php/Unit/Lang/VariableTest.php

This PR add a new language feature: Variables.
Sometime it is necessary to store a central value that is changing. Currently there was no support for this in Phel. Now you can define a variable to store a changing value. Example:
```
(def foo (var 10))
(deref foo) # Evaluates to 10
(set! foo 20) # Set foo to 20
(deref foo) # Evaluates to 20
(swap! foo + 2) # Evaluates to 22
(deref foo) # Evaluates to 22
```

Support for variables

---

src/phel/test.phel

The test library was still using the old table data structure for the stats. This has now been replaced with a persistent data structure in combination with a variable.

Use persistent hash map for tests stats

---

src/php/Lang/PhelArray.php
src/php/Lang/Set.php
src/php/Lang/Table.php

- Added `@deprected` to PhelArray, Set & Table classes in favor of the new persistent data structures (that were introduced here: https://github.com/phel-lang/phel-lang/pull/244)
What are the next step we should do to get rid of these deprecated classes? I guess we should check that the core tests are using the persistent data structures, and the old ones aren't used anywhere else. Is there something else we need to keep in mind to do this, @jenshaase?

Add deprecated note to old collection data structures

---

src/phel/core.phel
src/php/Compiler/Analyzer/Analyzer.php
src/php/Compiler/Analyzer/AnalyzerInterface.php
src/php/Compiler/Analyzer/Ast/DefInterfaceMethod.php
src/php/Compiler/Analyzer/Ast/DefInterfaceNode.php
src/php/Compiler/Analyzer/Ast/DefStructInterface.php
src/php/Compiler/Analyzer/Ast/DefStructMethod.php
src/php/Compiler/Analyzer/Ast/DefStructNode.php
src/php/Compiler/Analyzer/Ast/PhpClassNameNode.php
src/php/Compiler/Analyzer/Environment/GlobalEnvironment.php
src/php/Compiler/Analyzer/Environment/GlobalEnvironmentInterface.php
src/php/Compiler/Analyzer/TypeAnalyzer/AnalyzePersistentList.php
src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/DefInterfaceSymbol.php
src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/DefStructSymbol.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/DefInterfaceEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/DefStructEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/MethodEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitterFactory.php
src/php/Lang/Symbol.php
tests/php/Integration/Fixtures/Def/definterface-with-methods.test
tests/php/Integration/Fixtures/Def/definterface.test
tests/php/Integration/Fixtures/Def/defstruct-interface-without-methods.test
tests/php/Integration/Fixtures/Def/defstruct-one-interface.test
tests/php/Integration/Fixtures/Def/defstruct-two-interfaces.test
tests/php/Integration/Fixtures/Fn/fn-this-parameter.test
tests/php/Unit/Compiler/Analyzer/Environment/GlobalEnvironmentTest.php
tests/php/Unit/Compiler/Analyzer/SpecialForm/DefStructSymbolTest.php
tests/php/Unit/Compiler/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitterTest.php

This PR add a new language feature: interfaces.
It is now possible to define interfaces with `definterface`. It is possible to add zero or more function to a interface. Each function must have a least one parameter. This parameter is bound to `$this` in PHP. Examples:
```
(definterface MyInterfaceWithoutFunctions)
(definterface MyInterfaceWithOneFunction
(foo [this]))
(definterface MyInterfaceWithTwoFunction
(foo [this])
(bar [this a b]))
(definterface MyInterfaceWithDocComments
(foo [this] "my optional comment")
(bar [this a b] "my other optional comment"))
```
Furthermore it is now possible to use these interface in structs. Structs can implement zero or more interfaces. Examples:
```
(definterface MyInterfaceWithoutMethods)
(defstruct* my-type-with-one-interface-without-methods [v] …
```

Define interface and let struct implement them

---

.github/CODE_OF_CONDUCT.md

Add basic code of conduct for the project
https://contributor-covenant.org
> I got the inspiration by PHPUnit's code of conduct: https://github.com/sebastianbergmann/phpunit/blob/master/.github/CODE_OF_CONDUCT.md

Add contributor-covenant code of conduct

---

src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/DefInterfaceSymbol.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/DefInterfaceEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/DefStructEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/MethodEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/PhpNewEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/PhpObjectCallEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/RecurEmitter.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/TryEmitter.php

Minor cleanup for most of the output emitters
- Refactor DefInterfaceSymbol
- Refactor some Output Emitters
Non related to this PR but worth mentioning: I discovered last week that if you press `.` in a PR (in GitHub), you will get the PR diff in an online VS. It's awesome.

Refactoring some output emitters

---

.github/CONTRIBUTING.md
Readme.md

We have currently duplicated some "contributing" guides on the `Readme.md` and on the new `CONTRIBUTING.md`.
Unify the contributing section in one single place.
- Move the `Contributing` section from the `Readme.md` to `.github/CONTRIBUTING.md`

Move contributing section from Readme.md to CONTRIBUTING.md

---

src/phel/test.phel
src/php/Command/CommandFacade.php

TextExceptionPrinter::create method is not available anymore #397
Get rid of the PHP exception when the test has an exception on runtime
Use the CommandFacade to get the ExceptionPrinter in the `print-error` function.
I intentionally didn't add the `public function getExceptionPrinter(): ExceptionPrinterInterface` to the `CommandFacadeInterface` because I considered that we don't really want to expose that method to other modules, and the FacadeInterface is the contract that modules has between each other. If we end-up needing this function, we could add it, but till then I think it's ok keeping it like this.
There is a PHP runtime exception due to calling an non-existing method.
The Exception is being rendered properly.

Expose ExceptionPrinter from CommandFacade

---

.github/workflows/ci.yml

We weren't using the real `matrix.operating-system` on the CI. We were using it only for the name, but not on the real field `runs-on: XXX`. Anyway, I was really wondering if we really need PHP for different OS... at least not for now. 
However, I was wondering if running the different type of tests on different jobs, so we could run them in parallel and check the timing as well for them independently. 
- Remove the `operating-system: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]`, which we even didn't use properly 😂. Maybe we could reimplement this in the future if we find the need.
- Split the tests by types to run on different jobs.

Separate the CI tests on diff jobs

---

.github/workflows/ci.yml
composer.json
composer.lock

PHP 7.4 version is not a supported version (only for security fixes) https://www.php.net/supported-versions.php
For this reason, we decided to upgrade the project to use `PHP>=8.0`. 
Another big plus: we'll be able to use PHP 8.0 features: https://www.php.net/releases/8.0/en.php 
Upgrade the composer (and dependencies) to require `PHP>=8.0`.
Here you can see the composer diff changes from the lock using this awesome tool `composer-lock-diff`. I did the composer update and `cp composer.lock composer-php80.lock`, and afterwards `git checkout master` so I can compare the current `composer.lock` from master to the new generated `composer.lock `.
> ~/.composer/vendor/bin/composer-lock-diff --from=composer.lock --to=vendor/composer-php80.lock
``` …
```

Upgrade PHP to require >=8.0

---

src/phel/core.phel
tests/phel/test/core/for-loop.phel

The `for` loop macro is a nice and readable way to iterate over data structures. However, if you need to do reductions to a single value, like summing all number in a list, you have have to use the `reduce` function instead. The reduce function is very handy if the function is already defined but it is much harder to read if you include a custom function.
In this PR I will introduce a `:reduce` keyword in the `for` loop to create reductions that are easier to read.
Example:
```
(reduce 
(fn [sum x] (if (even? x) (+ sum x) sum))
0
[1 2 3 4])
(->> [1 2 3 4]
(filter even?)
(reduce + 0))
(for [x :in [1 2 3 4]
:when (even? x)
:reduce [sum 0]]
(+ sum x))
```
This PR add a `:reduce` option to the for-loop. This allows us to use the list comprehension loop also for task that normally would …

Added a :reduce option for the for-loop

---

src/php/Build/BuildFactory.php
src/php/Build/Compile/ProjectCompiler.php
src/php/Compiler/CompilerFacade.php
src/php/Compiler/CompilerFacadeInterface.php
src/php/Compiler/CompilerFactory.php

In the `Build` module, instead of creating a new instance of an object from the `Compiler` module, we should delegate that communication to the `CompilerFacade`.
Don't create object from external modules directly inside a module.
- Add `encodeNs()` to the `CompilerFacade`
- Inject the `CompilerFacade` into the `ProjectCompiler`

Keep Munge creation inside its module

---

tests/php/Integration/Formatter/FormatterFacadeTest.php

The test generator with name 'Map' was duplicated, like this:
```php
yield 'Map' => [
[
'{:x 1',
':y 2}',
],
[
'{:x 1',
'  :y 2}',
],
];
yield 'Map' => [ 
'actualLines' => ['{ :a 1 :b 2 }'],
'expectedLines' => ['{:a 1 :b 2}'],
];
```
The funny thing was that the first one was a failing test (with a wrong expectation; it had two white spaces instead of one). While the second test was working as expected, and this was translated into having a non-running failing test on the fixtures.
Changing the name of any of these generators make the failed test explicit.
- Fix the failing `yield 'Map'` test, and renamed to `yield 'Indent map block'`.
- Remove unnecessary/duplicated test `yield 'Indent'`.
- Rename all yield names to something more descriptive.

Fix formatter facade tests

---

src/php/Formatter/Command/FormatCommand.php
src/php/Formatter/FormatterFacade.php
src/php/Formatter/FormatterFactory.php
tests/php/Integration/Formatter/FormatterFacadeTest.php

We were exposing in the facade a `format()` method which is used only on feature tests.
The idea of this PR is to move deeper this method to make it less exposure to the exterior, and to make it more difficult someone from outside can use it.
Also, I have marked the `getFormatter()` method as `@internal` to make it more explicit.

Move format() inside FormatCommand

---

src/php/Compiler/Analyzer/Ast/NsNode.php
src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/NsSymbol.php
src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
tests/php/Integration/Fixtures/Keyword/keywords.test
tests/php/Integration/Fixtures/Ns/munge-ns.test
tests/php/Integration/Fixtures/Ns/require-file.test
tests/php/Unit/Build/Extractor/NamespaceExtractorTest.php

This commit adds a new feature to load php files in the ns statement. This
can, for example, be used to load the composer autoload file. Example
```
(ns myapp
(:require-file "vendor/autload.php"))
```
The :require-file import ins transformed into a require_once statement in PHP.
The file is loaded before any other :require import.
Fixes: #409

Added feature to require php files in ns statement.

---

src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
tests/php/Integration/Fixtures/Def/definterface-instance-of.test
tests/php/Integration/Fixtures/Def/definterface-with-methods.test
tests/php/Integration/Fixtures/Def/definterface.test
tests/php/Integration/Fixtures/Def/namespace-def.test
tests/php/Integration/Fixtures/Keyword/keywords.test
tests/php/Integration/Fixtures/Let/loop-destructure.test
tests/php/Integration/Fixtures/New/new-from-alias.test
tests/php/Integration/Fixtures/Ns/munge-ns.test
tests/php/Integration/Fixtures/Ns/require-file.test
tests/php/Integration/Fixtures/Ns/require.test
tests/php/Integration/Fixtures/Ns/use.test
tests/php/Integration/Fixtures/Try/catch-from-ns-use.test

Currently the compiled code contains lines like this:
```php
\Phel\Compiler\Analyzer\Environment\GlobalEnvironmentSingleton::getInstance()->setNs("hello-world\\boot");
```
Remove this line from the compiled code because it is not needed.

Fixes #408: Remove calls to GlobalEnvironmentSingleton in compiled code

---

src/phel/repl.phel
src/phel/test.phel
src/php/Interop/ExportFinder/FunctionsToExportFinder.php
src/php/Lang/Registry.php

Replace the string method name `getDefintionMetadata` to `getDefinitionMetadata` from PHP and Phel code.
(Notice the missing `i` on `Definition` word) 😄

Override method getDefintionMetadata by getDefinitionMetadata

---

src/php/Build/Compile/ProjectCompiler.php
src/php/Compiler/Analyzer/Environment/GlobalEnvironment.php
src/php/Lang/Registry.php
tests/php/Integration/Build/Command/CompileCommandTest.php

The compile command had the problem that the cached version was not really working. After executing the command the first time everything went fine, because the was not cached files. In the second run the command mostly fails because of undefined functions. The problem here is that the `GlobalEnvironment` didn't know of functions in the cached files.
This PR fixes the problem by importing the already compiled files.

Fixes the compile command when it rebuild using a cache.

---

src/phel/core.phel
src/php/Command/Shared/Exceptions/Extractor/FilePositionExtractor.php
src/php/Compiler/Parser/ExpressionParser/AtomParser.php
src/php/Formatter/Domain/Rules/Indenter/LineIndenter.php
src/php/Run/Domain/Repl/InputResult.php

Use new PHP 8.0 functions to improve readability. 
- Use `str_starts_with()` & `str_contains()` instead of `strpos()`

Use str_starts_with & str_contains instead of strpos

---

.github/workflows/docker.yml
docker/repl/Dockerfile
docker/repl/composer.json

I want to give new user a very easy way got try out the REPL.
This PR adds a Dockerfile to build a Docker image that starts the REPL. A GitHub actions workflow is added to automatically publish a version to docker hub. 
New user can use this image to try out Phel simply by running
```
docker run -it --rm phellang/repl
```
I already a push a image to Docker Hub. So you can try it out yourself.
* Added a Dockerfile
* Added a new GitHub Actions workflow.
---
Next: Update the website with this command

Docker quickstart container

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/sequence-functions.phel

Merging maps or nested data structures is a common problem in programming. This PR will add new functions that may be very useful.
The first function is call `merge-with`. `merge-with` takes a two-arity function `f` and a unlimited number of hash maps. It will merge these hash maps as in `merge` but in case two maps have the same key it will call `f` with the left and the right value. Example:
```
(merge-with + {:a 1 :b 2} {:b 3 :c 4}) # Evaluates to {:a 1 :b 5 :c 4}
```
The second function is called `deep-merge`. This function will recursively merge nested data structures. Hash maps will be merged as in `merge`, vectors will be concatenated, sets will be united. Example:
```
(deep-merge {:a {:b {:c [:d]}}} {:a {:b {:c [:e] :f :g}}} # Evaluates to {:a {:b {:c [:d :e] :f :g}}}
```
* Added: …

Added two new merge function: merge-with and deep-merge

---

CHANGELOG.md
src/phel/core.phel
src/phel/html.phel
src/phel/http.phel
src/phel/repl.phel
src/phel/test.phel
src/php/Lang/Keyword.php
src/php/Lang/NamedInterface.php
src/php/Lang/Symbol.php
tests/phel/test/core.phel

`\Phel\Lang\Symbol` and `\Phel\Lang\Keyword` have both the methods `getName`, `getNamespace` and `getFullName`.
Put the three methods into a unified Interface and let Symbol and Keyword implement these interface. Additionally, add functions in Phel's core library to call these methods. Use the new functions in the rest of the code.
The function `name` and `full-name` also support strings. This is quite useful to convert Hash Map to PHP arrays. Example:
```
(def data {:foo "value" "bar" "value2"})
(->> data
(map-indexed (fn [k v] [(name k) v]))
(flatten)
(apply php-associative-array))
```
* Added: `NamedInterface` interface for Symbol and Keyword
* Added: `name` function
* Added: `namespace` function
* Added: `full-name` function
* Use the added function in the rest of the code.

NamedInterface

---

CHANGELOG.md
src/phel/http.phel
tests/phel/test/http.phel

Improve `phel\http`
* Added: `http/uri-from-string` function
* Added: Uri structs implements `Stringable` interface
* Added: `http/response-from-map` function
* Deprecated: `http/create-response-from-map` in favor of `http/response-from-map`
* Added: `http/response-from-string` function
* Deprecated: `http/create-response-from-string` in favor of `http/response-from-string`
* Added: `attributes` field to `request` struct. Allows developers to enrich the request with custom data
* Added: `http/request-from-map` function

Improve phel\http

---

CHANGELOG.md
src/php/Compiler/Analyzer/Analyzer.php
src/php/Compiler/Emitter/OutputEmitter/LiteralEmitter.php
tests/php/Integration/Fixtures/MacroExpand/return-array.test
tests/php/Unit/Compiler/Analyzer/AnalyzeLiteralTest.php

With this commit it is possible to emit PHP array literals. This is useful if a macro wants to return a PHP array.
Macros can currently only return Phel data structures. For some use cases it is useful to also allow PHP arrays as return type.
This PR makes it possible to emit PHP array literals. Example:
```clojure
(defn build-some-php-array []
(php/array 1 2))
(defmacro macro-returns-php-array []
(build-some-php-array))
```

Emit PHP array literals

---

composer.json
composer.lock
phel
src/php/Command/CommandConfig.php
src/php/Command/CommandFactory.php
src/php/Interop/InteropConfig.php
src/php/Run/RunConfig.php
tests/php/Integration/Printer/PrinterTest.php

- Update dependencies, highlight the `gacela-project/gacela` to version `0.14.0`
- Adjust the `Gacela::bootstrap()` config method
- Switch deprecated methods `getApplicationDir()` to new ones `getAppDir()`

Update Gacela to 0.14 version

---

src/php/Phel.php
tests/php/Benchmark/Phel/PhelBench.php

When updating to gacela 0.14 we forgot to update the `Phel::run()` method, on which we are actually using `Gacela::bootstrap()`. This happened mainly because we didn't have any tests covering/using this code.
- Update the `Phel::run()` internal method to use the new gacela version code.
- Add a Bench test which is executing the `Phel::run()` so we wont have this problem in the future anymore.

Update gacela bootstrap in phel static helper

---

src/php/Printer/Printer.php
src/php/Printer/PrinterInterface.php
src/php/Printer/TypePrinter/AnonymousClassPrinter.php
src/php/Printer/TypePrinter/ArrayPrinter.php
src/php/Printer/TypePrinter/BooleanPrinter.php
src/php/Printer/TypePrinter/FnPrinter.php
src/php/Printer/TypePrinter/KeywordPrinter.php
src/php/Printer/TypePrinter/NonPrintableClassPrinter.php
src/php/Printer/TypePrinter/NullPrinter.php
src/php/Printer/TypePrinter/NumberPrinter.php
src/php/Printer/TypePrinter/ObjectPrinter.php
src/php/Printer/TypePrinter/PersistentHashSetPrinter.php
src/php/Printer/TypePrinter/PersistentListPrinter.php
src/php/Printer/TypePrinter/PersistentMapPrinter.php
src/php/Printer/TypePrinter/PersistentVectorPrinter.php
src/php/Printer/TypePrinter/ResourcePrinter.php
src/php/Printer/TypePrinter/StringPrinter.php
src/php/Printer/TypePrinter/StructPrinter.php
src/php/Printer/TypePrinter/SymbolPrinter.php
src/php/Printer/TypePrinter/ToStringPrinter.php
src/php/Printer/TypePrinter/TypePrinterInterface.php

- Update Printer module to use some new PHP 8.0 features
- use mixed keyword
- use `array_is_list` function
- Fix a (really hidden) bug  inside the `createObjectTypePrinter()`
- The condition checking the `AbstractPersistentStruct` was never reached

Printer module using php80

---

composer.json
composer.lock
phel
src/php/Phel.php

Gacela got a new version with some internal performance improvements.
- Update to latest Gacela 0.15

Update Gacela 0.15

---

CHANGELOG.md
src/phel/core.phel
src/php/Compiler/Compiler/CodeCompiler.php
src/php/Compiler/Compiler/CodeCompilerInterface.php
src/php/Compiler/Compiler/EvalCompiler.php
src/php/Compiler/Compiler/EvalCompilerInterface.php
src/php/Compiler/CompilerFacade.php
src/php/Compiler/CompilerFacadeInterface.php
tests/phel/test/core.phel

Add some more function to core library
The following functions have been added:
* `read-string`: Takes a string and returns the parsed expression
* `eval`: Takes a Phel form and evaluates it
* `compile`: Takes a Phel form and return the compiled PHP code.

Added read-string, eval and compile function to core library

---

phel
src/php/Console/ConsoleDependencyProvider.php
src/php/Console/ConsoleFactory.php
src/php/Console/Infrastructure/ConsoleBootstrap.php

Currently all console commands are created inside the `phel` file, the entry point of phel. I would delegate the responsibility of the command creation in another place like a Console module.
- Created a `ConsoleBootstrap` which extends Application Symfony Command.
- Define all phel commands inside the `ConsoleDependencyProvider`.

Create a ConsoleBootstrap

---

.github/workflows/ci.yml
composer.json
composer.lock
phpstan.neon
src/php/Lang/Collections/LinkedList/PersistentList.php

Similar like Psalm, PHPStan is another static analysis tool for PHP which catches a lot of other things that Psalm doesn't. Currently it's not possible to install PHPStan at any higher level but the minimum (level 1; the highest level in PHPStan is 9|max).
Use PHPStan to spot potential bugs in the project, and so improve the quality overall. Starting with the min level and upgrading it to higher levels step by step.
- Install PHPStan with level 1 - the lowest level (for now).
- In the `phpstan.neon` you can see that I'm excluding a lot of paths. The reason: `Child process error (exit code 255): PHP Fatal error:  Allowed memory size of 541065216 bytes exhausted (tried to allocate 262144 bytes) in [...]`, so I thought a quick way to get rid of those "memory size" exceptions could be just …

Install PHPStan

---

composer.json
phpmetrics-config.json

As I did recently in Gacela, I thought it would be interesting to have a similar setup for Phel regarding this phpmetric setup.
See: https://github.com/gacela-project/gacela/pull/139
This is a cool alternative to have an overlook of the project structure, and look for potential spots for improvements.
Optimize the usage for phpmetric dev tool.
- Define a `phpmetrics-config.json` and updates the composer script `metrics-report`

Improve phpmetrics usage

---

composer.json
composer.lock
src/php/Build/BuildFacade.php
src/php/Build/BuildFacadeInterface.php
src/php/Build/BuildFactory.php
src/php/Build/Command/CompileCommand.php
src/php/Build/Compile/ProjectCompiler.php
src/php/Console/ConsoleDependencyProvider.php
tests/php/Integration/Build/Command/CompileCommandTest.php

Currently, the creation of the commands is done in the Factory of the module, on which we inject its dependencies. But then, the command it's not self-instanciable" and it needs the Factory or the Facade (which later uses its Factory) to create that command... it's a bit to ugly, because the command start depending on a lot of things, like other external facades or internal dependencies. 
But, this is odd, a Command (like a Controller) is part of the infrastructure code that should have access to the Facade of its module, and the Facade knows how to deal with other Facades and perform the logic that it's required.
This PR is a refactoring example of making the `CompileCommand` depending only on the `CompileFacade` using `getFacade()` method.
Simplify the creation of the Commands in …

Remove constructor from CompileCommand

---

src/php/Console/ConsoleDependencyProvider.php
src/php/Formatter/Command/FormatCommand.php
src/php/Formatter/Domain/Exception/FilePathException.php
src/php/Formatter/Domain/PathsFormatter.php
src/php/Formatter/FormatterFacade.php
src/php/Formatter/FormatterFacadeInterface.php
src/php/Formatter/FormatterFactory.php
src/php/Formatter/Infrastructure/Command/FormatCommand.php
src/php/Formatter/Infrastructure/IO/FileIoInterface.php
src/php/Formatter/Infrastructure/IO/SystemFileIo.php
tests/php/Integration/Formatter/Command/Format/FormatCommandTest.php
tests/php/Integration/Formatter/FormatterFacadeTest.php

Similar as it was done in https://github.com/phel-lang/phel-lang/pull/461 & https://github.com/phel-lang/phel-lang/pull/465
The goal is to allow the creation of the `FormatCommand` directly, and for this we need to get rid of its dependencies.
Refactor the `FormatCommand` using internally its `FormatterFacade`. This way, its communication will be via its facade;
- accesible via getFacade(), a new feature of the latest version from Gacela with use FacadeResolverAwareTrait;
- see: https://gacela-project.com/docs/facade/#use-the-facade-from-your-infrastructure-layer

Refactor FormatCommand to use the Facade

---

src/php/Console/ConsoleDependencyProvider.php
src/php/Run/Command/TestCommand.php
src/php/Run/RunFacade.php
src/php/Run/RunFacadeInterface.php
src/php/Run/RunFactory.php
src/php/Run/Runner/NamespaceCollector.php
tests/php/Benchmark/Command/CommandBench.php
tests/php/Integration/Run/Command/Test/TestCommandProjectFailure/TestCommandProjectFailureTest.php
tests/php/Integration/Run/Command/Test/TestCommandProjectSuccess/TestCommandProjectSuccessTest.php

Similar as it was done in https://github.com/phel-lang/phel-lang/pull/461 
The goal is to allow the creation of the `TestCommand` directly, and for this we need to get rid of its dependencies.
Refactor the `TestCommand` using internally its RunFacade. This way, its communication will be via its facade; 
- accesible via `getFacade()`, a new feature of the latest version from Gacela with `use FacadeResolverAwareTrait;`
- see: https://gacela-project.com/docs/facade/#use-the-facade-from-your-infrastructure-layer

Remove constructor for TestCommand using RunFacade instead

---

CHANGELOG.md
src/php/Run/Domain/Repl/ReplCommandSystemIo.php

Issue: https://github.com/phel-lang/phel-lang/issues/467
There seems to be a bug when `readline_info('library_version')` return `null`. And this is an error because `stripos()` expect a non-nullable string as first argument.
- Use an empty string when `readline_info('library_version')` returns null

Fix ReplCommandSystemIo when internal library_version is null

---

src/php/Console/ConsoleDependencyProvider.php
src/php/Run/Infrastructure/Command/RunCommand.php
src/php/Run/RunFacade.php
src/php/Run/RunFacadeInterface.php
src/php/Run/RunFactory.php
tests/php/Benchmark/Command/CommandBench.php
tests/php/Integration/Run/Command/Run/RunCommandTest.php

Similar as it was done in:
- https://github.com/phel-lang/phel-lang/pull/466
- https://github.com/phel-lang/phel-lang/pull/461
- https://github.com/phel-lang/phel-lang/pull/465
The goal is to allow the creation of the `RunCommand` directly, and for this we need to get rid of its dependencies.
Refactor the `RunCommand` using internally its `RunFacade`. This way, its communication will be via its facade;
- accesible via `getFacade()`, a new feature of the latest version from Gacela with `use DocBlockResolverAwareTrait;`
- see: https://gacela-project.com/docs/facade/#use-the-facade-from-your-infrastructure-layer

Refactor RunCommand to use DocBlockResolverAwareTrait

---

src/php/Console/ConsoleDependencyProvider.php
src/php/Interop/Domain/ExportCodeGenerator.php
src/php/Interop/Infrastructure/Command/ExportCommand.php
src/php/Interop/InteropFacade.php
src/php/Interop/InteropFacadeInterface.php
src/php/Interop/InteropFactory.php
tests/php/Integration/Interop/Command/Export/ExportCommandTest.php

Similar as it was done in:
- https://github.com/phel-lang/phel-lang/pull/466
- https://github.com/phel-lang/phel-lang/pull/461
- https://github.com/phel-lang/phel-lang/pull/465
The goal is to allow the creation of the `ExportCommand` directly, and for this we need to get rid of its dependencies.
Refactor the `ExportCommand` using internally its `InteropFacade`. This way, its communication will be via its facade;
- accesible via `getFacade()`, a new feature of the latest version from Gacela with `use DocBlockResolverAwareTrait;`
- see: https://gacela-project.com/docs/facade/#use-the-facade-from-your-infrastructure-layer

Refactor ExportCommand to use DocBlockResolverAwareTrait 

---

composer.json
composer.lock
phel
src/php/Phel.php
tests/php/Integration/Build/Command/CompileCommandTest.php
tests/php/Integration/Interop/Command/Export/ExportCommandTest.php
tests/php/Integration/Run/Command/Repl/ReplCommandTest.php
tests/php/Integration/Run/Command/Run/RunCommandTest.php
tests/php/Integration/Run/Command/Test/TestCommandProjectFailure/TestCommandProjectFailureTest.php
tests/php/Integration/Run/Command/Test/TestCommandProjectSuccess/TestCommandProjectSuccessTest.php

Now it's mandatory to define the appConfig path.
- Upgrade gacela from 0.17 to 0.19
- Define the appConfig for all feature tests who needs some config values

Update gacela 0.19

---

.github/workflows/ci.yml
composer.json
composer.lock

1. `.github/workflows/ci.yml` -> `actions/cache` (3.0.3 => 3.0.4)
- `phpstan/phpstan` (1.7.15 => 1.8.0)
- `symfony/console` (v5.4.9 => v5.4.10)
- `symfony/deprecation-contracts` (v2.5.1 => v2.5.2)
- `symfony/event-dispatcher-contracts` (v2.5.1 => v2.5.2)
- `symfony/service-contracts` (v2.5.1 => v2.5.2)
- `symfony/string` (v5.4.9 => v5.4.10)
- `vimeo/psalm` (4.23.0 => 4.24.0)
- `symfony/deprecation-contracts` (v2.5.1 => v2.5.2)
- `symfony/service-contracts` (v2.5.1 => v2.5.2)
- `symfony/event-dispatcher-contracts` (v2.5.1 => v2.5.2)
- `symfony/string` (v5.4.9 => v5.4.10)
- `symfony/console` (v5.4.9 => v5.4.10)
- `phpstan/phpstan` (1.7.15 => 1.8.0)
- `vimeo/psalm` (4.23.0 => 4.24.0)

Update composer dependencies

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/basic-sequence-operation.phel
tests/phel/test/core/type-operation.phel

Currently, it's not possible to use the `count` function with strings. 
This is also affecting the `empty?` function, which uses the `count`, you get an error: `object is not countable`.
Allow **checking emptiness** in strings.
- Allow `(empty? "")` and `(empty? "any string")`
- Display a more descriptive error when using an string with `(count "")` function

Support strings in `empty?`

---

.editorconfig
.gitattributes

This PR adds two config files to the `phel` project which I consider they are very important.
- What is [editorconfig](https://editorconfig.org/)?
**EditorConfig** helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a **file format** for defining coding styles. EditorConfig files are easily readable and they work nicely with version control systems.
- What are [gitattributes](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes)?
You can tell Git not to export certain files or directories when generating an archive. If there is a subdirectory or file that you don’t want to include in your archive file but that you do want checked into your project, you can determine those …

Add .editorconfig & .gitattributes files

---

composer.json
composer.lock
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/TrySymbol.php
src/php/Lang/Collections/LinkedList/PersistentList.php
src/php/Lang/Collections/Map/ArrayNodeIterator.php
src/php/Lang/Collections/Map/HashCollisionNode.php
src/php/Lang/Collections/Map/IndexedNodeIterator.php
src/php/Lang/Collections/Map/PersistentArrayMap.php
src/php/Lang/Collections/Map/PersistentHashMap.php
src/php/Lang/Collections/Map/TransientArrayMap.php
src/php/Lang/Collections/Vector/PersistentVector.php
src/php/Lang/Collections/Vector/RangeIterator.php
src/php/Lang/Collections/Vector/SubVector.php
src/php/Lang/Collections/Vector/TransientVector.php
src/php/Lang/Hasher.php
src/php/Lang/Registry.php
src/php/Lang/TypeFactory.php
src/php/Printer/Printer.php
src/php/Printer/TypePrinter/StructPrinter.php
tests/php/Unit/Formatter/Domain/Rules/Zipper/ArrayZipper.php
tests/php/Unit/Lang/Collections/Struct/FakeStruct.php

Remove `ext-json`, as it is not necessary anymore [since PHP 8.0](https://php.watch/versions/8.0/ext-json), also, update dependencies 😃
**Edit**: Because of updating the dependencies, the CI pipeline was not working, I had to run `./vendor/bin/php-cs-fixer fix` command to make it green.

Remove ext-json from composer

---

src/php/Interop/Infrastructure/Command/ExportCommand.php
tests/php/Unit/Compiler/Analyzer/SpecialForm/ForeachSymbolTest.php

`@{}` is the deprecated old table data structure, which was removed on `0.6.0` (2022-02-02).
Use the map syntax `{}` instead of old table syntax `@{}`.

Fix map typo

---

composer.json
composer.lock

- Update to latest gacela version
- More details: https://github.com/gacela-project/gacela/releases/tag/0.25.0
- And also some minor versions for dev dependencies
```
phel-lang/ (misc/update-gacela-0.25✗) $ ~/.composer/vendor/bin/composer-lock-diff --from=/tmp/composer-dev.lock --to=composer.lock  
+-----------------------+--------+--------+------------------------------------------------------------------+
| Production Changes    | From   | To     | Compare                                                          |
+-----------------------+--------+--------+------------------------------------------------------------------+
| gacela-project/gacela | 0.24.0 | 0.25.0 | https://github.com/gacela-project/gacela/compare/0.24.0...0.25.0 | …
```

Update gacela 0.25

---

src/php/Build/BuildFactory.php
src/php/Build/Domain/Compile/FileCompiler.php
src/php/Build/Domain/Extractor/NamespaceExtractor.php
src/php/Build/Domain/IO/FileIoInterface.php
src/php/Build/Infrastructure/Command/CompileCommand.php
src/php/Build/Infrastructure/IO/SystemFileIo.php
tests/php/Unit/Build/Extractor/NamespaceExtractorTest.php

Instead of using `file_get_contents()` inside the Domain layer, inject `FileIoInterface` to `FileCompiler` and `NamespaceExtractor`.

Inject FileIoInterface to FileCompiler and NamespaceExtractor

---

src/php/Phel.php
tests/php/Integration/Phel/PhelTest.php

We have a function `Phel::run()` to run a concrete namespace from phel. However, there might be some need to have some concrete `argv` in that particular namespace. Right now, the only way is to setup manually from the outside like 
```php
$GLOBALS['argv'][] = 'additional arguments';
```
To be able to add your additional phel arguments when running a concrete namespace with `Phel::run()` as an optional argument to that function.
- Add a new argument to the `Phel::run()` funtion ➡️  `array|string $argv`

Add argv argument to Phel::run()

---

src/phel/core.phel
tests/phel/test/core/boolean-operation.phel

I think it would be practical if we have a function that checks if a value is inside a collection. Similar as the `contains?` 🤔 
- Add `contains-value?` function

Add contains-value? function

---

src/phel/core.phel
src/php/Build/Domain/Compile/FileCompiler.php
src/php/Build/Domain/IO/FileIoInterface.php
src/php/Build/Infrastructure/IO/SystemFileIo.php
src/php/Compiler/CompilerFacade.php
src/php/Compiler/Domain/Emitter/EmitterResult.php
src/php/Compiler/Domain/Emitter/FileEmitter.php
src/php/Compiler/Domain/Emitter/StatementEmitter.php
tests/php/Integration/IntegrationTest.php

- Decouple I/O from `FileCompiler`
- Rename `getCode()` to `getPhpCode()`
- Refactor StatementEmitter
- Make `CompileOptions` argument optional

Refactoring FileCompiler and making CompileOptions optional

---

tests/php/Integration/Formatter/FormatterFacadeTest.php
tests/php/Integration/IntegrationTest.php
tests/php/Integration/Interop/CallPhelTest.php

Since gaclea@0.29 you have to explicitly call `Gacela::bootstrap()` before using Gacela Facade/Factory/Config/DependencyProvider classes.

Fixing broken tests

---

composer.json
composer.lock
psalm.xml

- Sort alphabetically the `composer.json` dependencies, and
- Add `psalm/plugin-phpunit` to composer-dev
This plugin removes the warning in all PHP tests 👇🏼 😄

Add psalm/plugin-phpunit dependency

---

.github/workflows/ci.yml

As @localheinz mentions on his https://github.com/gacela-project/gacela/pull/214 PR, the `set-output` command is deprecated.
> Check this link for more reference: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix: Do not use deprecated set-output command

---

composer.json
composer.lock
psalm.xml
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/Binding/Deconstructor/NullBindingDeconstructor.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/TrySymbol.php
src/php/Compiler/Domain/Emitter/OutputEmitter/LiteralEmitter.php
src/php/Compiler/Domain/Lexer/TokenStream.php
src/php/Formatter/Domain/Rules/IndentRule.php
src/php/Lang/AbstractFn.php
src/php/Lang/AbstractType.php
src/php/Lang/Collections/HashSet/PersistentHashSet.php
src/php/Printer/TypePrinter/NullPrinter.php
tests/php/Integration/Formatter/Command/Format/FormatCommandTest.php

Update `phel` to PHP 8.0.2
In order to upgrade Symfony dependencies to 6.x, we need to update the minimum PHP version from 8.0 to 8.0.2.
Also, Psalm was upgraded to 5.1. (reference https://github.com/phel-lang/phel-lang/commit/821457b50f5e6c00a19912bcbc0d33228ad627f3#r91961860)

Update psalm 5.1

---

.github/workflows/ci.yml
tests/php/Unit/Lang/Collections/Struct/FakeStruct.php

When running PHP 8.2 there are warning messages over the `FakeStruct` class
Fix the warning messages
- Remove `__meta` property from `FakeStruct`
- Run CI tests using PHP 8.2 as well

Fix FakeStruct warnings

---

tests/phel/test/core.phel

- Add phel tests to ensure struct with types
While working with structs I thought at the beginning that there might be a bug when comparing structs with different types. Fortunately, I was wrong and the mistake was somewhere else. This test helped me understand that there is no bug on this behaviour, so I think it is useful to keep this test.

Add phel test-struct-with-types

---

src/phel/json.phel

I just noticed that the docs for the json functions are in the wrong place, because they are ignored in our API page
I easily noticed this because `valid-key?` is the only function with docs in the API page.
Fix the docs for the `phel\json` functions
- Move between the function name and the arguments the function docs

Fix docs for json functions

---

CHANGELOG.md
src/php/Build/Infrastructure/Command/BuildCommand.php
src/php/Console/ConsoleDependencyProvider.php
tests/php/Integration/Build/Command/BuildCommandTest.php

The current `phel compile` command is inside the `Build` module:
I like that actually, because the `Compiler` module is full of other responsibilities. That's where you find the Analyzer, Compiler, Emitter, Evaluator, Lexer, Parser, and Reader, aka that's where the phel code gets interpreted/transformed to the php code:
However, when having a command named `compile` it would make sense to go and look inside the Compiler module (at least for me). 
Instead of moving the command from `Build` inside the `Compiler` (and loosing the Build module separation of concerns), the idea is to rename the command from `phel compile` to `phel build`, and keep the compile as alias for the build command.
- Rename the class CompileCommand to BuildCommand
- Add `phel compile` as alias for `phel build`

Rename command compile to build

---

CHANGELOG.md
phel-config.php
src/php/Build/BuildConfig.php
src/php/Build/BuildFactory.php
src/php/Build/Domain/Compile/ProjectCompiler.php
src/php/Command/Domain/Shared/Exceptions/Extractor/SourceMapExtractor.php
tests/php/Integration/Build/Command/config/phel-config.php
tests/php/Integration/Build/Command/src/failing.phel

Issue: https://github.com/phel-lang/phel-lang/issues/521
Add a new key-value to `phel-config.php` to be able to ignore certain files at compile time (by name or pattern path, for example).
- Add new config parameter `ignore-when-compiling`
- Ignore these path(s) when running the `phel compile` command

Allow ignore phel files when building the project

---

src/php/Compiler/Domain/Parser/Parser.php

Currently, we have the `Parser::readExpression()` method with a `D` grade in [Scrutinizer](https://scrutinizer-ci.com/g/phel-lang/phel-lang/code-structure/master/operation/Phel%5CCompiler%5CDomain%5CParser%5CParser::readExpression).
I think that is happening due to the multiple `return` statements the method has, hopefully  (but I am not 100% sure) with the `match` statement due to the single `return`, the qualification might improve.

Replace switch by match in Parser->readExpression()

---

CHANGELOG.md
src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php
tests/phel/test/core/math-operation.phel
tests/php/Unit/Compiler/Parser/ExpressionParser/AtomParserTest.php

Idea: https://github.com/phel-lang/phel-lang/discussions/563
We can use underscore for binary, octal and hexa but not decimal.
To be able to use underscore on decimal numbers. Supported from PHP 7.4
- Changed AtomParser to check for valid decimal numbers with underscores as well

Allow underscores in decimal numbers

---

phel-config.php
src/php/Formatter/FormatterConfig.php
src/php/Formatter/Infrastructure/Command/FormatCommand.php
tests/php/Integration/Formatter/Command/Format/FormatCommandTest.php

This is the implementation for ticket #568
The format command can be run without passing any paths. If no paths are being passed, the default paths "src" and "tests" should be used, as defined in the config.
In addition to the changes of the command, I updated the test cases to use the CommandTester from Symfony. This allows to run the command without having to mock the input and therefore allows to test the FormatterCommand without passing any paths.

Add default format paths

---

CHANGELOG.md
psalm.xml
src/php/Build/BuildConstants.php
src/php/Build/Domain/Compile/FileCompiler.php
src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
src/php/Shared/BuildConstants.php
src/php/Shared/CompilerConstants.php
tests/php/Integration/Build/Command/src/hello.phel
tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php

We can use the form `*compile-mode*` to identify if we are during building mode (former "compilation").
We renamed the command from `phel compile` to `phel build`, so it would make sense to use `*build-mode*` 
Deprecate `*compile-mode*` in favor of `*build-mode*`
- Create a constant for `BuildConstants::BUILD_MODE = '*build-mode*'`
- Moved constant from `GlobalEnvironment::PHEL_CORE_NAMESPACE` to `CompilerConstants::PHEL_CORE_NAMESPACE`
- Create a new dir `Shared` to store these new constants interfaces (`BuildConstants`, `CompilerConstants`)

Rename compile-mode to build-mode

---

CHANGELOG.md
src/phel/test.phel
src/php/Run/Domain/Test/TestCommandOptions.php
src/php/Run/Infrastructure/Command/TestCommand.php
tests/php/Unit/Run/Domain/Test/TestCommandOptionsTest.php

You can use the optional option `--testdox` in PHPUnit, which renders a nicer output. For example:
It would be handy to have such option when running the `phel test` command. 
I introduced a similar option for our `phel test`. It doesn't render the test-name (I didn't know how to do it), but I could render the test message. 
> **Note**: we can refactor it once we figure out how to use the test-name instead of the test message. At least when there is no test message.
> It's not as nice as the one from PHPUnit, but step by step 😄 
IDEA 1: Add the running/execution time for each test next to the text itself (see the PHPUnit screenshot).
IDEA 2: Add color for the **fail** and **pass** checks.

Add testdox option

---

src/php/Command/Domain/Finder/ComposerVendorDirectoriesFinder.php
src/php/Config/PhelConfigException.php
tests/php/Integration/Command/Domain/DirectoryFinder/ComposerVendorDirectoriesFinderTest.php
tests/php/Integration/Command/Domain/DirectoryFinder/testing-vendor/root-1/root-2/custom-src-2/hi.phel
tests/php/Integration/Command/Domain/DirectoryFinder/testing-vendor/root-1/root-2/phel-config.php
tests/php/Integration/Command/Domain/DirectoryFinder/testing-vendor/root-1/root-3/custom-src-3/hi.phel
tests/php/Integration/Command/Domain/DirectoryFinder/testing-vendor/root-1/root-3/phel-config.php
tests/php/Integration/Command/Domain/DirectoryFinder/wrong-testing-vendor/root-1/root-2/custom-src/hi.phel
tests/php/Integration/Command/Domain/DirectoryFinder/wrong-testing-vendor/root-1/root-2/phel-config.php

After merging https://github.com/phel-lang/phel-lang/pull/572 I wanted to quickly try it with my [phel-snake](https://github.com/Chemaclass/phel-snake) project and I found this error:
>**Note**: My bad, I forgot to add tests for this class, so this was a great opportunity to add some 💡 
Fix the bug 🐛 `Error : Cannot use object of type Phel\Config\PhelConfig as array`
- When doing the "require file" check if it's an array or a PhelConfig object before trying to access to the `SRC_DIRS `
- This way we keep total compatibility for both options, you can use the array version or the object version

PhelConfig not accessible as array

---

.gitignore
CHANGELOG.md
src/php/Phel.php

Gacela has a [file cache system](https://gacela-project.com/docs/bootstrap/#gacela-file-cache) with the resolved class names for the internal php modules, and by enabling we can get some performance optimisations. 
The final user wont notice anything, as they should have the `*.cache` pattern in their `.gitignore` file.
This can be easily disabled, anyway, in any project using gacela by defining in their config key values the `'gacela-cache-enabled'` as `false`; you can find it in `Gacela\Framework\ClassResolver\Cache\GacelaFileCache::KEY_ENABLED`.
```php
return [
'gacela-cache-enabled' => false,
\Gacela\Framework\ClassResolver\Cache\GacelaFileCache::KEY_ENABLED => false,
];
```
- Enable gacela cache file system
This is an example of how the gacela cache files are generated, so it is not …

Enable gacela cache by default

---

CHANGELOG.md
src/php/Compiler/Domain/Analyzer/Ast/GlobalVarNode.php
src/php/Compiler/Domain/Analyzer/Environment/NodeEnvironment.php
src/php/Compiler/Domain/Analyzer/Environment/NodeEnvironmentInterface.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpAPushSymbol.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpASetSymbol.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpAUnsetSymbol.php
src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/GlobalVarEmitter.php
src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/PhpArrayPushEmitter.php
src/php/Lang/Registry.php
src/php/Run/Infrastructure/Command/ReplCommand.php
tests/phel/test/core/sequence-operation.phel
tests/php/Integration/Fixtures/Call/php-push-global-reference.test
tests/php/Integration/Fixtures/Call/php-push.test
tests/php/Unit/Lang/RegistryTest.php

Issue: https://github.com/phel-lang/phel-lang/issues/578
Fix `php/push`, `php/aset` and `php/aunset` on native php arrays when using global definitions.
- Allowing using `getDefinitionReference()` that will be used when dealing with native php arrays

Fix apush, aset and aunset for global php arrays

---

src/php/Console/Infrastructure/ConsoleBootstrap.php
tests/phel/test/ci-should-fail.phel

Fixes #580 
CI should not pass when a Phel test is red.
https://github.com/phel-lang/phel-lang/actions/runs/4276054183/jobs/7443874528

CI not failing

---

composer.json
src/php/Api/ApiConfig.php
src/php/Api/ApiFacadeInterface.php
src/php/Api/ApiFactory.php
src/php/Api/Domain/PhelFnNormalizer.php
src/php/Phel.php
tests/php/Integration/Api/ApiFacadeTest.php

Currently, you have to pass a list with all namespaces which you are interested on knowing the functions via the Api.
Move the responsibility to the Api itself to retrieve all namespaces in case you don't specify anyone.

Use all ns by default

---

src/php/Api/Infrastructure/Command/DocCommand.php

Remove unnecessary array from `DocCommand`, because if `getPhelFunctions()` receive an empty list of ns then it will search for all of them.

Minor clean up for DocCommand

---

composer.json

Mutation Testing is a fault-based testing technique which provides a testing criterion called the Mutation Score Indicator (MSI). The MSI can be used to **measure the effectiveness of a test set** in terms of its ability to detect faults.
Mutation testing involves modifying a program in small ways. Each mutated version is called a Mutant. To assess the quality of a given test set, these mutants are executed against the input test set to see if the seeded faults can be detected. If mutated program produces failing tests, this is called a killed mutant. If tests are green with mutated code, then we have an escaped mutant.
Test suites are measured by the percentage of mutants that they kill. New tests can be designed to kill additional mutants.
>**Note**: Read more about mutation testing: …

Add infection

---

.gitattributes
.github/CONTRIBUTING.md
.github/git-hooks/init.sh
.github/git-hooks/pre-commit.sh
composer.json

- Move the `tools` dir to `.github`
- Delete `tools` folder
- Add `post-install-cmd` script to install git hooks when updating dependencies

Move githooks to /.github/git-hooks + run when composer install

---

src/php/Build/BuildFactory.php
src/php/Build/Domain/Compile/ProjectCompiler.php
src/php/Config/PhelOutConfig.php
tests/php/Integration/Build/Command/BuildCommandTest.php
tests/php/Integration/Build/Command/config/phel-config-no-namespace.php

Fixes #613.
Skip the PHP entrypoint creation when the Phel namespace isn't configured.
- Add a boolean attribute to `ProjectCompiler` that controls if the entrypoint will be created.
- Add a method in `PhelOutConfig` to determine whether the entrypoint should be created or not.
- Add the corresponding integration test

Do not create the entrypoint when namespace isn't set

---

src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php
tests/php/Unit/Compiler/Parser/ExpressionParser/AtomParserTest.php

Previously, symbols ending in zero were being parsed as numbers.
Fixes: #616
Fix a bug in the AtomParser were symbols ending in zero would be parsed as a decimal number.
It was happening because the decimal regex was structured as `^A|B$`, and that reads as:  
"(The beginning of a line followed by A) OR (B followed by a line end)"
Looks like the original intent was `^(A|B)$`, as in:
"The beginning of a line followed by (A OR B) followed by a line end"
- Fix decimal regex in AtomParser by wrapping the `OR` condition in a non-capturing group `(?: )`
- Add a regression test

Fix AtomParser decimal regex

---

CHANGELOG.md
src/php/Command/Domain/Handler/ExceptionHandler.php

Issue: https://github.com/phel-lang/phel-lang/issues/614
Improve the dev experience when seen deprecated notes.
Define a custom register handler for deprecated notes. This will render a similar output as the current "notices" in the terminal + add a new entry to the `error.log`.

Define a custom registerDeprecatedHandler

---

.gitignore
composer.lock

Hi,
This PR was created after a discussion with @Chemaclass.
Basically, since `phel` should be considered as compiler, it should therefore be reproducible.
Without `composer.lock`, it is impossible to ensure reproducibility of the package.
This PR fixes this. 
Created using PHP 8.0.30

chore: add `composer.lock`

---

src/php/Build/Domain/Compile/DependenciesForNamespace.php
src/php/Build/Domain/Extractor/NamespaceExtractor.php
src/php/Command/CommandConfig.php
src/php/Command/Domain/Finder/DirectoryFinder.php
src/php/Run/Domain/Runner/NamespaceCollector.php
tests/php/Integration/Build/Command/config/phel-config-no-namespace.php
tests/php/Integration/Build/Command/config/phel-config.php
tests/php/Integration/Interop/Command/Export/config/phel-config.php

How to reproduce the issue:
1. `mkdir -p ~/Code/phel-lang`
2. `cd ~/Code/phel-lang`
3. `git clone https://github.com/phel-lang/phel-lang`
4. `cd phel-lang`
5. `composer install`
6. `cd ..`
7. `./phel-lang/bin/phel`
I believe that the REPL should work from any directory, not only from the source directory.
This PR is a WIP since I've been trying to find for a solution... but couldn't find anything working yet.

Fix `phel repl` when not in the phel directory

---

bin/phel

Support `phel --version`
Define hardcoded version when creating the Symfony Application
```php
$bootstrap = new ConsoleBootstrap(name: 'Phel', version: 'v0.11.0');
```

Define custom --version

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json
composer.lock
docker/repl/Dockerfile

PHP 8.0 is not supported anymore. Latest PHP version is 8.3, and for what respect to Phel, we should aim to use the latest or close to the latest PHP version to run. I don't see a reason why not.
https://www.php.net/supported-versions.php
Require a more modern PHP version.
- Require min PHP 8.2 to run Phel

Require min php version 8.2

---

psalm.xml
src/php/Compiler/Domain/Parser/ParserNode/ListNode.php
src/php/Formatter/Domain/Rules/Indenter/InnerIndenter.php

Closes https://github.com/phel-lang/phel-lang/issues/464
Increase Psalm level 1 by adding to ignore some checkers.
All of them are `Mixed...`, that is, we depend on third-party tools like `Symfony` or `Gacela`, as a result, we need to deal with the type of var that was defined originally as `mixed`.
I suggest ignoring all of them as they only will make the code polluter with more lines and unnecessary information most of them.

Increase Psalm level 1

---

CHANGELOG.md
src/php/Formatter/Infrastructure/Command/FormatCommand.php

Allow using `fmt` to format the phel code
You can now use both:
- `bin/phel format`
- `bin/phel fmt`
> Inspired by `cargo fmt` command - for rust

Add fmt as alias for format

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/sequence-functions.phel

In Phel-lang, when using the interleave function with two collections where one contains nil values, the nil values are ignored in the resulting sequence. This differs from Clojure, where nil values are included in the resulting sequence.
Fixes: https://github.com/phel-lang/phel-lang/issues/681
Store in a var the size of the first collection and iterate until the first collection is completely looped through.
Inspired by the current Clojure behaviour:
> Kudos to @smeghead - https://github.com/phel-lang/phel-lang/issues/681#issuecomment-2059230380

Fix interleave with nil values

---

src/php/Build/BuildFacade.php
src/php/Build/Domain/Compile/FileCompiler.php
src/php/Build/Domain/Compile/ProjectCompiler.php
src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php

The `**build-mode**` is ignore when `require_once $targetFile;` in the `FileCompiler`.
We need to enable/disable the build mode on `ProjectCompiler` and also on the `FileCompiler`; before it was only at `ProjectCompiler`, and this resulted in bugs when loading a cached filed from the `FileCompiler`.

fix: BuildMode when transpiling the code

---

CHANGELOG.md
src/phel/str.phel
tests/phel/test/str.phel

Add the namespace phel\str and add the string function below.
split join reverse upper-case replace replace-first trim-newline capitalize lower-case upper-case trim triml trimr blank? starts-with?  ends-with?  includes?  re-quote-replacement escape index-of last-index-of split-lines
I created a string manipulation function library that is not available in phel, using clojure as a reference.
https://github.com/smeghead/phel-str
This is a pull request to introduce the functions of this library to phel.
You can now use the added functions.
```
phel:1> (require phel\str)
phel\str
phel:2> (str/join ["a" "b" "c"])
abc
phel:3> (str/upper-case "hello!")
HELLO!
```
added `src/phel/str.phel` file includes functions. and added namespace `phel\str`.

feat: add string functions.

---

tests/php/Integration/Api/ApiFacadeTest.php
tests/php/Integration/Build/Command/BuildCommandTest.php

Remove the output text while running the PHP tests
BEFORE
AFTER

Remove output from tests

---

CHANGELOG.md
src/php/Compiler/Infrastructure/Munge.php
tests/phel/test/core/threading-macros.phel

Closes: https://github.com/phel-lang/phel-lang/issues/694
Allow using $ as named param to for any macro
Add `$` => `__DOLLAR__` to the `Munge::DEFAULT_MAPPING`

Fix $ as named parameter in macros

---

CHANGELOG.md
src/php/Config/PhelBuildConfig.php
tests/php/Unit/Compiler/Config/PhelBuildConfigTest.php

Bug found: https://x.com/azjezz/status/1791104988904673706 by @azjezz
Use a custom `normalizePhpExtension()` instead of `rtrim()` on `PhelBuildConfig`

Fix avoid using trim on PhelBuildConfig

---

CHANGELOG.md
src/php/Config/PhelConfig.php
src/php/Config/PhelExportConfig.php
tests/php/Unit/Compiler/Config/PhelConfigTest.php

RIght now, it's almost mandatory to create your own phel-config.php file, because the default values are 
Using `src/phel` for the default src directory. Using `test/phel` for the default test directory.
But for a phel project, the phel code will live most luckely under src directly.
Smooth the starting DX when using phel with the min setup as possible.
- Using `src` for the default src directory
- Using `test` for the default test directory
Update docs: https://phel-lang.org/documentation/getting-started/#manually-initialize-a-new-project-using-composer  
> https://github.com/phel-lang/phel-lang.org/blob/master/content/documentation/getting-started.md 
There is no need to create `phel-config.php`, only if you would like to customize the default behaviour.

Change default config dirs

---

CHANGELOG.md
src/php/Run/Domain/Repl/MissingDependencyException.php
src/php/Run/Domain/Repl/ReplCommandSystemIo.php

The current codebase for the REPL (Read-Eval-Print Loop) system lacks proper handling of missing PHP extensions, which can lead to runtime errors and poor user experience. The goal of this pull request is to add a mechanism to check for required PHP extensions and handle cases where they are missing.
The goal of this PR is to improve the robustness and user-friendliness of the REPL system by adding a check for the required readline PHP extension. If the extension is not loaded, a custom exception will be thrown to inform the user about the missing dependency.
- Created a new class MissingDependencyException in the src/php/Run/Domain/Repl namespace.
- This class extends RuntimeException and provides a static method missingExtension for creating exceptions with a message about the missing …

fix: check for readline extension in REPL

---

tests/php/Integration/Run/Command/Repl/ReplCommandTest.php

Remove unnecessary condition inside `ReplCommandTest::buildDataProviderFromDirectory()`. 
That same condition is duplicated right above.

Remove unnecessary condition in ReplCommandTest

---

phpunit.xml.dist
src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php
tests/php/Unit/Compiler/Parser/ExpressionParser/AtomParserTest.php

When evaluating a negative hexadecimal number in the REPL:
> phel:1> -0x1
The following deprecation notice is raised:
> [2024-06-08T13:22:33+00:00] Error Unknown(22527) found!
message: "Invalid characters passed for attempted conversion, these have been ignored"
file: phel-lang/src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php:141 
context: {"errno":8192}
It is also raised for positively-signed hexadecimal numbers.
Phel evaluates hexadecimal numbers using the
[hexdec()](https://php.net/hexdec) function, which only accepts unsigned values; therefore, `hexdec()` raises a deprecation notice in the REPL.
The goal of this P.R. is to solve the cause of the deprecation notice.
- `hexdec()` also does not accept the underscores in numbers. For this reason, Phel removes them before …

fix: deprecation notice for signed hexadecimals

---

phpunit.xml.dist
src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php
tests/php/Unit/Compiler/Parser/ExpressionParser/AtomParserTest.php

When evaluating a negative octal number in the REPL:
> phel:1> -01
The following deprecation notice is raised:
> [2024-06-08T13:51:08+00:00] Error Unknown(22527) found!
message: "Invalid characters passed for attempted conversion, these have been ignored"
file: phel-lang/src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php:153 
context: {"errno":8192}
It is also raised for positively-signed octal numbers.
Phel evaluates octal numbers using the [octdec()](https://php.net/octdec) function, which only accepts unsigned values; therefore, `octdec()` raises a deprecation notice in the REPL.
The goal of this P.R. is to solve the cause of the deprecation notice.
- `octdec()` also does not accept the underscores in numbers. For this reason, Phel removes them before passing the octal …

fix: deprecation notice for signed octals

---

phpunit.xml.dist
src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php
tests/php/Unit/Compiler/Parser/ExpressionParser/AtomParserTest.php

When evaluating a negative binary number in the REPL:
> phel:1> -0b1
The following deprecation notice is raised:
> [2024-06-07T10:58:02+00:00] Error Unknown(22527) found!
message: "Invalid characters passed for attempted conversion, these have been ignored"
file: phel-lang/src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php:129
context: {"errno":8192}
It is also raised for a positively-signed binary number.
Phel evaluates binary numbers using the [bindec()](https://php.net/bindec) function, which only accepts unsigned values; therefore, `bindec()` raises a deprecation notice in the REPL.
The goal of this P.R. is to solve the cause of the deprecation notice.
- `bindec()` also does not accept the underscores in numbers. For this reason, Phel removes them before passing the binary …

fix: deprecation notice about signed binary number in REPL

---

CHANGELOG.md
src/php/Lang/Collections/Vector/PersistentVector.php
src/php/Lang/Collections/Vector/PersistentVectorInterface.php
src/php/Lang/Collections/Vector/SubVector.php
tests/phel/test/core/basic-sequence-operation.phel

closes: #709 
Fixed an issue where an error would occur when passing a Vector as the second argument to the `cons` function.
Making List and Vector compatible in the `cons` function
`ConsInterface` has been added to `PersistentVectorInterface`.
With my current knowledge of the `phel-lang` source code, I was not able to implement it with performance in mind. Therefore, it is in a state where it just works for the time being. Could you please review and fix it?

Compatibility of lists and vectors in the cons function

---

CHANGELOG.md
src/php/Compiler/Domain/Analyzer/Ast/FnNode.php
src/php/Compiler/Domain/Analyzer/Exceptions/AnalyzerException.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DefSymbol.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/InvokeSymbol.php
tests/php/Integration/Fixtures/Call/global-call.test
tests/php/Integration/Fixtures/Call/php-fn-reference.test
tests/php/Integration/Fixtures/Def/definterface-instance-of.test
tests/php/Integration/Fixtures/Def/definterface.test
tests/php/Integration/Fixtures/Def/defn-meta.test
tests/php/Integration/Fixtures/Foreach/foreach-expr.test
tests/php/Integration/Fixtures/MacroExpand/macro-expand.test
tests/php/Integration/Fixtures/MacroExpand/return-array.test
tests/php/Integration/Fixtures/Ns/munge-ns.test
tests/php/Integration/Fixtures/Try/throw-expr.test
tests/php/Unit/Compiler/Analyzer/SpecialForm/InvokeSymbolTest.php

Issue: https://github.com/phel-lang/phel-lang/issues/704
Fail on compilation time when passing wrong number of args to a function.
Added a `'min-arity'` meta data to the `FnNode` and check that when analyzing the `InvokeSymbol`

feat: Check mandatory function parameters during compile time.

---

src/php/Api/Infrastructure/Command/DocCommand.php

https://github.com/phel-lang/phel-lang/pull/720#issuecomment-2156510943 
The display process of the table format depends on the `tput` command.
So, if you dont have `tput` the `doc` command wont cause an error.
- Use env `$COLUMNS` instead of `tput`

Fix doc command

---

CHANGELOG.md
src/phel/str.phel
tests/phel/test/str.phel

Closes: #735
Results of `str/split` are returned in the correct order even when the number of elements is greater than 16.
Removed unnecessary `php-array-to-map` calls.
```clojure
phel:1> (require phel\str)
phel\str
phel:2> (str/split-lines "str-1\nstr-2\nstr-3\nstr-4\nstr-5\nstr-6\nstr-7\nstr-8\nstr-9\nstr-10\nstr-11\nstr-12\nstr-13\nstr-14\nstr-15\nstr-16\nstr-17\n")
[str-1 str-2 str-3 str-4 str-5 str-6 str-7 str-8 str-9 str-10 str-11 str-12 str-13 str-14 str-15 str-16 str-17 ]
```

Fix result elements order of split

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/sequence-functions.phel

Closes: #737 
The `pred` function is not executed when an empty vector is searched for by the `find` function, etc.
Fix `loop` recursion termination conditions to evaluate using `empty?`.

Fix `find` function for an empty vector

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/boolean-operation.phel
tests/phel/test/core/sequence-functions.phel

Closes: #741
The pred function is not executed when an empty vector is searched for by the `some?` function.
Fix loop recursion termination conditions to evaluate using `empty?`.

Fix `some?` function for an empty vector

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/binding.phel

Closes: #748
No error occurs when an atom value is specified in the `body` of the `binding` function.
In `binding` macro expansion, the way `body` is expanded has been corrected.

Fix `binding` function for atom body

---

tests/phel/test/special-forms.phel

REPL can redefine vars though documentation told it can't.
(https://github.com/phel-lang/phel-lang/issues/725)
Unifies the result to either of.
https://github.com/t-matsudate/phel-lang/commit/f22b86ae17134e3d6ccac7f0a6ef010658c516c6
https://github.com/t-matsudate/phel-lang.org/commit/301f080106f3dac0b3f9cab072eaa1040916bbb0

Added: Tests to proof documentations.

---

composer.json
composer.lock
src/php/Api/ApiFactory.php
src/php/Api/ApiProvider.php
src/php/Build/BuildFactory.php
src/php/Build/BuildProvider.php
src/php/Command/CommandFactory.php
src/php/Command/CommandProvider.php
src/php/Compiler/CompilerFactory.php
src/php/Compiler/CompilerProvider.php
src/php/Console/ConsoleFactory.php
src/php/Console/ConsoleProvider.php
src/php/Formatter/FormatterFactory.php
src/php/Formatter/FormatterProvider.php
src/php/Interop/InteropFactory.php
src/php/Interop/InteropProvider.php
src/php/Run/RunFactory.php
src/php/Run/RunProvider.php
tests/php/Integration/Run/Command/Repl/ReplCommandTest.php

In Gacela 1.8 the `DependencyProvider` is deprecated in favor of `Provider`
- Upgrade Gacela to `^1.8`
- Use the `AbstractProvider` instead of `DependencyProvider`

Upgrade gacela 1.8

---

tests/php/Integration/Api/ApiFacadeTest.php

Remove the `skipped` statement from `ApiFacadeTest`.
Using the combination of `@runInSeparateProcess` and `@preserveGlobalState disabled` the test works.
src: https://docs.phpunit.de/en/9.6/annotations.html?highlight=preserveGlobalState#preserveglobalstate

Run in separate process the ApiFacadeTest

---

CHANGELOG.md
src/php/Command/Application/CommandExceptionWriter.php
src/php/Command/Application/TextExceptionPrinter.php

Right now, I dont know the root of the error when I try to build a project but there is an error somewhere hidden. 
Related: https://github.com/jasalt/phel-wp-plugin/issues/4
Improve DX for errors.
- use the parent error, which contains the information of the actual error.
- this will show the actual error origin coming from PHP transpiled code
Terminal:
And on the `data/error.log`:
Terminal:
And on the `data/error.log`:

Display the root source file on errors

---

src/php/Api/Application/PhelFnNormalizer.php
src/php/Api/Domain/PhelFnLoaderInterface.php
src/php/Api/Infrastructure/Command/DocCommand.php
src/php/Api/Infrastructure/PhelFnLoader.php
src/php/Api/Transfer/PhelFunction.php

Related: https://github.com/phel-lang/phel-lang.org/issues/95
- Decouple the `url` from the `docs` field
- Use the original data (from the phel docs) in case the overriding field does not contain custom data
- Useful to override partial data from existing phel functions
> Once this is merged, we have to create a new patch release for phel-lang, and then upgrade the docs project (to update `composer.lock`) and rebuild it

Support override docs data on PhelFnLoader

---

CHANGELOG.md
src/php/Phel.php

Fixes: https://github.com/phel-lang/phel-lang/issues/772 & https://github.com/jasalt/phel-wp-plugin/issues/12
- Call `FilesystemFacade->clearAll()` on `Phel::run()` by @smeghead 
>  https://github.com/phel-lang/phel-lang/issues/772#issuecomment-2497949005

Fix temporary files are not being removed on Phel::run()

---

composer.lock
src/php/Console/Infrastructure/ConsoleBootstrap.php
src/php/Lang/Keyword.php
src/php/Phel.php

It might fix: https://github.com/phel-lang/phel-lang/issues/781
Get rid of PHP deprecation messages due to PHP 8.4
- Use nullable arg when using null as default value
- Upgrade gacela [1.9.1](https://github.com/gacela-project/gacela/releases/tag/1.9.1)

Fix deprecated messages

---

src/phel/core.phel

This behavior was easy to miss without reading sources or [test code](https://github.com/phel-lang/phel-lang/blob/f89f425685ba79f4ad5a2fc10190417f6da0d0a7/tests/phel/test/core/boolean-operation.phel#L131).
Improve function documentation visible also at https://phel-lang.org/documentation/api/#all
Suggestion for the wording:
```
"Returns true if `(pred x)` is logical true for every `x` in collection `xs` 
or if `xs` is empty. Otherwise returns false."
```
Had hard time fitting all into one sentence..

Document `all?` returns true for empty collection

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/threading-macros.phel
tests/php/Integration/Api/ApiFacadeTest.php

Add Clojure influenced macro saving some typing while mutating objects. Sending PR to core as I had trouble using it from a utility library (https://github.com/phel-lang/phel-lang/issues/784) but nevertheless this could be useful to include in `core.phel`. Similar macro has been in Clojure core library since 1.0 ([clojuredocs.org](https://clojuredocs.org/clojure.core/doto)).
I followed example of existing threading macros in `core.phel` which seem to originate from Clojure core also and added this near those as it seemed fitting.
One note is that I was left wondering why `core.phel` threading macros don't preserve the metadata as Clojure does, is it not possible in Phel or could it be that it just has been left unimplemented while the equivalent functions for reading/writing metadata …

Add doto macro

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core.phel
tests/php/Integration/Api/ApiFacadeTest.php

Add another macro from Clojure (since 1.0). Allows rough timing of executed code with execution time printed in stdout and execution result being returned to caller.
Test only checks that printing happens and expression value is returned as expected. Testing that measurement is actually effective might be useful but it gets bit tricky. I didn't notice any tests for the macro in Clojure core either so it's probably not that important. Macro is generally used ad-hoc during development and not as something a running system would rely on to produce correct results.

Add `time` macro

---

.github/workflows/ci.yml

I noticed there is this weird error when @jasalt tried creating a PR https://github.com/phel-lang/phel-lang/pull/795
Make sure the CI workflow is stable
Use latest working version according to the docs: 
https://github.com/actions/cache?tab=readme-ov-file#creating-a-cache-key

fix: workflow cache v4

---

src/phel/core.phel
tests/phel/test/core.phel
tests/php/Integration/Api/ApiFacadeTest.php

It does similar validation to Clojure in somewhat verbose way as private assert-args macro was left out:
https://github.com/clojure/clojure/blob/ce55092f2b2f5481d25cff6205470c1335760ef6/src/clj/clojure/core.clj#L1849
Opinions / improvement ideas welcome.
Noting these are quite popular in general and I have been missing them quite often..

Add if-let and when-let macros

---

CHANGELOG.md
src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/CallEmitter.php
tests/php/Unit/Compiler/Emitter/OutputEmitter/NodeEmitter/CallEmitterTest.php

fix #729 
``` 
(ns test)
(php/echo "Hi!") 
```
The above Phel code will compile to the following PHP code.
``` 
<?php 
// /usr/src/src/example.phel 
// ;;AAEA,OAAC,KAAD,MAAA,CAAA 
return echo("Hi!"); 
```
``echo`` is a language construct that does not return a value. It appears that a syntax error occurs when a language construct that does not return a value is placed after ``return`.
`php/echo` should work as well as `php/print`.
Replace `php/echo` with `print` when outputting to PHP so that it is not affected by `echo`, a language construct that does not return a value.
The concern is that the PHP `echo` is not executed even though it is listed as `php/echo`.
If it should be important to run PHP `echo`, there is a way to create a wrapper function and call the wrapper function instead of …

fix: Fix `php/echo` does not work #729

---

CHANGELOG.md
src/php/Lang/Collections/Map/ArrayNode.php
tests/phel/test/core.phel

close #786 
When adding elements to a HashMap with more than 16 elements, a Notice message may appear.
When adding an element to a HashMap with more than 16 elements, a Notice message may not be displayed.
In ArrayNode.php, line 53, you used `==` to compare objects. In ambiguous comparisons, a cast to int was sometimes performed and a Notice message was displayed, so I changed it to `===`.

fix: Fix Hash-map malfunction notice #786

---

CHANGELOG.md
src/phel/str.phel
tests/phel/test/str.phel

- use multibyte functions in `capitalize`, `lower-case`, and `upper-case`
- test these functions with multibyte text

Improve string case functions

---

CHANGELOG.md
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DefStructSymbol.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DoSymbol.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/NsSymbol.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpNewSymbol.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpObjectCallSymbol.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/RecurSymbol.php
src/php/Lang/Collections/LinkedList/PersistentList.php
src/php/Lang/Collections/Vector/AbstractPersistentVector.php
src/php/Lang/Collections/Vector/SubVector.php

- Replaced loose comparisons with strict null checks in the “do” special form handler to avoid type juggling
- Updated interface iteration in DefStructSymbol to use strict null comparison for safer loops
- Ensured namespace imports iterate with strict null checks in NsSymbol
- Applied the same strict null comparison updates in object creation and method call analyzers
- Revised collection iterators to check for null strictly, preventing unintended truthiness

Fix null checks on Analyzer forms

---

CHANGELOG.md
src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
tests/php/Unit/Compiler/Analyzer/Environment/GlobalEnvironmentTest.php

Fixes:  https://github.com/phel-lang/phel-lang/issues/750
- prevent accessing private symbols via `:refer`
- add regression test for resolving private definitions through refer

Fix private symbol refer resolution

---

CHANGELOG.md
src/phel/core.phel
src/php/Api/Infrastructure/PhelFnLoader.php
src/php/Compiler/Domain/Analyzer/Ast/DefExceptionNode.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/AnalyzePersistentList.php
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DefExceptionSymbol.php
src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/DefExceptionEmitter.php
src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitterFactory.php
src/php/Lang/Symbol.php
tests/php/Integration/Api/ApiFacadeTest.php
tests/php/Integration/Fixtures/Def/defexception.test
tests/php/Unit/Compiler/Analyzer/AnalyzePersistentListTest.php
tests/php/Unit/Compiler/Analyzer/SpecialForm/DefExceptionSymbolTest.php

Closes: https://github.com/phel-lang/phel-lang/issues/194
- introduce `defexception` macro & special form to declare new exception types
- add `DefExceptionNode` and emitter to generate PHP classes
- support resolving `defexception*` in analyzer and output emitter
- document the macro in `PhelFnLoader`
- add unit and integration tests for exception definitions

Implement defexception special form

---

CHANGELOG.md
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/NsSymbol.php
src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php

Fixes: https://github.com/phel-lang/phel-lang/issues/766
- keep REPL helper macros after evaluating an ns form
- load required namespaces when ns forms are evaluated in the REPL

Fix REPL ns evaluation

---

src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
tests/php/Unit/Compiler/Analyzer/Environment/GlobalEnvironmentTest.php

Relates: https://github.com/phel-lang/phel-lang/issues/784
- GlobalEnvironment resolves macros defined in namespaces that contain hyphens

Resolve macros in ns that contain hyphens

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/sequence-functions.phel
tests/php/Integration/Api/ApiFacadeTest.php

Closes: https://github.com/phel-lang/phel-lang/issues/826
- implement `phel->php` and `php->phel` for recursive conversion
- test roundtrip conversions
- update expected API function count

Add recursive PHP-Phel conversion functions

---

src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/InvokeSymbol.php
tests/php/Unit/Compiler/Analyzer/SpecialForm/InvokeSymbolTest.php

Relates: https://github.com/phel-lang/phel-lang/issues/784
- Fixed macro macroExpand to encode namespaces by replacing hyphens with underscores before fetching definitions, preventing null callable errors
- Introduced a unit test verifying macro calls in a hyphenated namespace function correctly, including necessary imports for Munge encoding

Fix macroExpand to encode ns by replacing hyphens with underscores

---

CHANGELOG.md
src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/DefStructEmitter.php
tests/php/Integration/Fixtures/Def/defstruct-interface-without-methods.test
tests/php/Integration/Fixtures/Def/defstruct-one-interface.test
tests/php/Integration/Fixtures/Def/defstruct-two-interfaces.test
tests/php/Integration/Fixtures/Def/defstruct.test
tests/php/Integration/Fixtures/Ns/munge-ns.test

Fixes: https://github.com/phel-lang/phel-lang/issues/778
- Declare class on `DefStructEmitter` only if it was not declared already with `class_exists`

Fix cannot reload user ns

---

CHANGELOG.md
src/phel/core.phel
src/phel/str.phel
src/phel/test.phel
tests/phel/test/core.phel
tests/phel/test/core/boolean-operation.phel
tests/php/Integration/Api/ApiFacadeTest.php

Deprecate `str-contains?` in favor of `phel\str\contains?`

Add phel\str\contains?

---

CHANGELOG.md
src/phel/repl.phel
tests/php/Integration/Run/Command/Repl/Fixtures/doc-deprecated.test

Display deprecated metadata on doc

Display deprecated metadata on doc

---

build/build-phar.php

Data directories are required by some vendor packages (e.g. symfony/string) so only exclude project specific folders.

Fix build-phar.php

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/function-operation.phel
tests/php/Integration/Api/ApiFacadeTest.php

- Introduced a new memoize function that caches a function’s return value for each argument set, improving performance on repeated calls
- Added corresponding tests ensuring the memoized function only executes the underlying function when necessary

Add memoize function

---

CHANGELOG.md
src/php/Printer/TypePrinter/StringPrinter.php
tests/php/Integration/Printer/PrinterTest.php
tests/php/Unit/Printer/TypePrinter/StringPrinterTest.php

Fixes: https://github.com/phel-lang/phel-lang/issues/856 by @jasalt 
- Update StringPrinter to support unicode chars

Fix repl prints unicode chars

---

CHANGELOG.md
tests/php/Integration/Compiler/Evaluator/RequireEvaluatorTest.php

Fix https://github.com/phel-lang/phel-lang/issues/860 by @jasalt
- Prevented `"Directory not empty"` warnings by adding a class-level temp directory property and cleaning it in tearDown after the generated files are cleared
- Updated the test to assign the temporary directory to the new property and removed the final rmdir call from the test

Fix trigger warning in RequireEvaluatorTest

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core.phel
tests/php/Integration/Api/ApiFacadeTest.php

Needed way to define `php/CONSTANT`'s dynamically in macro. With this it's possible e.g. `(symbol (str "php/" "MY-CONSTANT"))`.
Looked at [Janet](https://github.com/janet-lang/janet/blob/ddc122958be34a18edd754743851536b5a16a3cc/src/core/corelib.c#L337) and [Clojure](https://github.com/clojure/clojure/blob/da1c748123c80fa3e82e24fc8e24a950a3ebccd9/src/clj/clojure/core.clj#L591) implementations, Clojure having explicit namespace support seemed more robust so took more influence from it as it seems to match `\Phel\Lang\Symbol` class static methods also nicely. 
Not sure of best way to define two different arities and couldn't grasp the usage of `{:inline-arity ...}` in some core library functions but better ideas are welcome.
Noted one warning in test suite but it's not related to this …

Add `symbol`

---

.github/PULL_REQUEST_TEMPLATE.md

It seems easy to forget updating `CHANGELOG.md` with pull requests.
This adds a mention about it in the end of the pull request template.
For this PR I don't add a mention to it as it seems too meta.

Mention `CHANGELOG.md` in pull request template

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/sequence-functions.phel

Fixing https://github.com/phel-lang/phel-lang/issues/874

Fix `map` function exhaustion with empty collections

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/sequence-functions.phel
tests/php/Integration/Api/ApiFacadeTest.php

Add convenience function familiar from Clojure for working with maps.
Draft as diagnosing why `contains-value?` is not behaving correctly with `nil` value..

feat: add `select-keys` function

---

CHANGELOG.md
src/php/Lang/Collections/Map/ArrayNodeIterator.php
tests/php/Unit/Lang/Collections/Map/ArrayNodeIteratorTest.php

Fixes https://github.com/phel-lang/phel-lang/issues/882
- Update `ArrayNodeIterator` with `array_filter` to remove null values
> The behavior is correct. The difference removed "/y/" from the first set. The seemingly “random” order is just because sets in Phel are unordered.

Fix set difference errors with certain input

---

CHANGELOG.md
src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
tests/php/Integration/Run/RequireBuildMode/Fixtures/example/game.phel
tests/php/Integration/Run/RequireBuildMode/Fixtures/example/main.phel
tests/php/Integration/Run/RequireBuildMode/RequireBuildModeTest.php

Fixes: https://github.com/phel-lang/phel-lang/issues/571
When doing a :require the file is loaded without the *build-mode* (formerly known as *compile-mode*), and if that phel file is running any I/O, then that file gets loading first, blocking the execution of the program.
The `(:require namespace)` shouldn't load the code on build-mode on that scope, so we can avoid executing code that shouldn't be execute on the ns scope.
- Ensures `:require` imports don't run top-level code by setting `*build-mode*` to true while loading the namespace.
- Adds a test confirming that required modules no longer create files or trigger other side effects.

Fix require ns loading code without build-mode

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/sequence-functions.phel
tests/phel/test/core/sequence-operation.phel
tests/php/Integration/Api/ApiFacadeTest.php

- Introduced Clojure-style aliases `assoc`, `assoc-in` for adding entries and `dissoc`, `dissoc-in` for removing entries, enhancing map manipulation ergonomics
- Added tests validating the new aliases and updated integration coverage to reflect the additional core functions

Add Clojure-style aliases for assoc and dissoc

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/sequence-functions.phel
tests/php/Integration/Api/ApiFacadeTest.php

We want to enable infinite lists generated on run time.
- Extended `take` to handle PHP Traversable inputs, enabling safe slicing of generators and other iterables for infinite list scenarios
- Introduced an `iterate` function that yields an unbounded sequence by repeatedly applying a function to its previous result
- Added generator-based tests, including a naturals helper, to verify take and iterate with endless streams

Add iterate to core and extend take to handle generators

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/sequence-functions.phel
tests/php/Integration/Api/ApiFacadeTest.php

I find a bit confusing having reduce and reduce2, while the only diff is their arguments. 
Combine reduce and reduce2 functions
- Unified reduce to handle both (reduce f coll) and (reduce f val coll), eliminating the old reduce2 helper and routing all bitwise operations through the new reducer
- Revised sequence tests to cover the new zero-value behavior and dropped any dependency on reduce2

Combine reduce and reduce2

---

CHANGELOG.md
src/php/Run/Infrastructure/Command/ReplCommand.php
tests/php/Integration/Run/Command/Repl/Fixtures/require-current-dir.test
tests/php/Integration/Run/Command/Repl/ReplTestCommand.php
tests/php/Integration/Run/Command/Repl/util.phel

Related https://github.com/phel-lang/phel-lang/issues/902#issuecomment-3221169009 by @jasalt 
- Updated the REPL to include the current working directory in its search paths so functions defined alongside the REPL session can be resolved correctly
- Added a dedicated test module and fixture verifying that functions in the working directory are found and executed by the REPL

Fix REPL symbol resolution issue loading current dir

---

CHANGELOG.md
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/Binding/Deconstructor/MapBindingDeconstructor.php
tests/phel/test/core.phel
tests/php/Unit/Compiler/Analyzer/SpecialForm/Binding/Deconstructor/MapBindingDeconstructorTest.php

Resolves https://github.com/phel-lang/phel-lang/issues/905 by @jasalt 
I miss Clojure map destructuring semantics when writing Phel. It allows destructuring map keys with :keys and a vector of names with less repetition, and the reference to original can be kept with :as and a name.
- Add map destructuring with `:keys` and `:as`

Add map destructuring with keys and as

---

CHANGELOG.md
src/php/Compiler/Application/Lexer.php
tests/php/Integration/Compiler/Parser/ParserTest.php
tests/php/Unit/Compiler/Lexer/LexerTest.php

Most lisps as far as I know use `;` as comment character and Phel using `#` is a slight inconvenience when switching between languages. I thought initially that maybe `;` is avoided cause of it's strong meaning in PHP, but then I'm interested to know what practical implications it would have if it was allowed as a alternative comment character in Phel. 
This PR experiments with adding that as alternative to the current `#` comment character in lexer.
Tests show green which is a good sign.
Thoughts?
With this, following syntax is valid:
```clojure
(ns testing-semicolon)
;; Demo comment
(defn hello []
(print "hello world"))
(hello)  ; Nice
```
Added benefit is also that it works better with Clojure syntax highlighting rules.

Add ; as alternative comment symbol

---

CHANGELOG.md
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/FnSymbol.php
tests/phel/test/core/fn-map-body.phel

Fix https://github.com/phel-lang/phel-lang/issues/922
The hashmap literal {:value x} being the function body seems to not get parsed as the function correctly with latest changes incorrectly resulting to nil.
Correct hash-map metadata parsing

Fix func metadata parsing conflict with literal hashmap

---

CHANGELOG.md
src/php/Command/CommandConfig.php

The deafult error log file was pointing to the data folder, which might end up into an error itself if the execution does not have permissions to create such folder in case it does not exist. Therefore, as default path for the error_log file, it will be in the same place of the execution of phel itself.
Make sure there is no need to create a new folder for the default error_log file for phel.
- Change the 'data/error.log' to  'phel-error.log' for the `DEFAULT_ERROR_LOG_FILE`

Update default error log file

---

CHANGELOG.md
src/phel/core.phel
src/php/Compiler/Domain/Reader/GensymContext.php
src/php/Compiler/Domain/Reader/QuasiquoteTransformer.php
tests/php/Integration/Compiler/Reader/ReaderTest.php

Resolves https://github.com/phel-lang/phel-lang/issues/919 
In macros, symbols generated with (gensym) often require an extra let form around the quoted forms for binding them to names. 
While either could improve working with generated symbols in macros, to me Clojure's behavior seems slightly more advanced and there would be potentially more code that would be easier to port to Phel with less structural changes. Hash character however might not be applicable as it's used for comments, maybe `$` could do.
```clojure
(defmacro time
"Evaluates expr and prints the time it took.  Returns the value of
expr."
{:added "1.0"}
[expr]
`(let [start# (. System (nanoTime))
ret# ~expr]
(prn (str "Elapsed time: " (/ (double (- (. System (nanoTime)) start#)) 1000000.0) " msecs"))
ret#))
```
- Add …

Add macro auto-gensym syntax

---

CHANGELOG.md
src/php/Console/Application/ArgvInputSanitizer.php
src/php/Console/ConsoleFactory.php
src/php/Console/Infrastructure/ConsoleBootstrap.php
tests/php/Integration/Run/Command/Run/Fixtures/argv-script.phel
tests/php/Integration/Run/Command/Run/RunTestCommand.php

Fixes https://github.com/phel-lang/phel-lang/issues/933
The PHP side argument parsing for phel command seems to grab all flag arguments like `--example` or `-h` that come after `phel run <script-name>`, this makes it impossible to use them as part of with Phel script command line interface.
- Enhanced the console bootstrap to sanitize argv, ensuring that when running Phel scripts via phel run, flag-style arguments after the script path are preserved instead of being consumed by the CLI

Allow passing cli flags args to phel run scripts

---

CHANGELOG.md
src/php/Api/Application/PhelFnNormalizer.php
src/php/Api/Application/ReplCompleter.php
src/php/Api/Domain/PhelFnLoaderInterface.php
src/php/Api/Infrastructure/PhelFnLoader.php
src/php/Api/Transfer/PhelFunction.php
tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php

Related to https://github.com/phel-lang/phel-lang/issues/942 by @jasalt 
Enable easy use of the docs without markdown format from `getPhelFunctions()`
- Change `fnSignature` to `signature`
- Add `rawDoc` as doc without markdown wrapper
> Keeping Backwards Compatibility (BC).

Add rawDoc to PhelFunction

---

CHANGELOG.md
src/php/Api/Application/PhelFnNormalizer.php
src/php/Api/Infrastructure/Command/DocCommand.php
src/php/Api/Transfer/PhelFunction.php
tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php

Closes https://github.com/phel-lang/phel-lang/issues/947 by @jasalt 
- Remove the rawDoc attr and function
- Deprecate PhelFunction methods in favor of public properties

Deprecate PhelFunction methods in favor of public props

---

CHANGELOG.md
src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
tests/php/Integration/Run/Command/Repl/Fixtures/file-dir-empty.test

Closes https://github.com/phel-lang/phel-lang/issues/948 by @jasalt 
- Return empty string for `__FILE__` and `__DIR__` in the REPL

Better handling FILE and DIR constants

---

CHANGELOG.md
src/phel/core.phel
tests/phel/test/core/meta.phel

The meta function did not work for non objects
Allow meta to work on objects and any other definition

Fix meta on definitions

---

CHANGELOG.md
src/php/Api/Application/PhelFnNormalizer.php
src/php/Api/Transfer/PhelFunction.php
src/php/Formatter/Domain/Rules/IndentRule.php
src/php/Formatter/Domain/Rules/Indenter/ListIndenter.php
tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php

Relates https://github.com/phel-lang/phel-lang.org/issues/137 
Enable knowing when a function is mark as deprecated; and being able to read any particular interesting data saved in the function's metadata.
- Add the metadata to the PhelFunction objects

Add meta to PhelFunction

---

CHANGELOG.md
src/php/Printer/TypePrinter/PersistentMapPrinter.php
src/php/Run/Domain/Test/TestCommandOptions.php
tests/php/Unit/Printer/TypePrinter/PersistentMapPrinterTest.php

Closes https://github.com/phel-lang/phel-lang/issues/957 by @jasalt

Add comma separator between key value pairs in the hash-map printer

---

src/phel/core.phel

Current behavior of [`argv`](https://github.com/phel-lang/phel-lang/blob/df802d378328a573624d63d7c6b684498527b1ba/src/phel/core.phel#L47) is a little bit odd, the output being an PHP Array:
```
./vendor/bin/phel repl
Welcome to the Phel Repl (v0.21.0-beta#231768b)
Type "exit" or press Ctrl-D to exit.
phel:1> argv
<PHP-Array ["./vendor/bin/phel", "repl"]>
```
While not essential, this would need to be converted to a Phel vector in user code adding some extra noise.
PR changes it to Phel vector:
```
./bin/phel repl
Welcome to the Phel Repl (v0.21.0-beta#1c3900b)
Type "exit" or press Ctrl-D to exit.
phel:1> argv
["./bin/phel" "repl"]
```
As `vector` is not declared in `core.phel` yet, I followed example how `\Phel` class static methods are called in following def's of `list`, `vector` and so …

`argv` as Phel vector instead of PHP array

---

.github/workflows/ci.yml
CHANGELOG.md
src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/FnSymbol.php
tests/phel/test/core/pre-post-conditions.phel

Closes https://github.com/phel-lang/phel-lang/issues/967 
Instead of using native php assert (which requires `zend.assertions=1`), we need to find another way to have such pre/post assertions
- Use custom if-throw for `:pre/:post` metadata conditions

Use custom if-throw for pre/post metadata conditions

---

CHANGELOG.md
src/php/Api/Infrastructure/Command/DocCommand.php

Closes: https://github.com/phel-lang/phel-lang/issues/978 by @JesusValeraDev 
When calling `phel doc`, it returns the information as a table. However, while building other tools that wants to know the outcome of this command, this output as a table is not useful; it would be great to have an optional parameter `--format={table|json}` (default "table")
- Add `--format` json option to `phel doc` command

Add format json to doc command

---

CHANGELOG.md
src/php/Api/Infrastructure/PhelFnLoader.php
src/php/Build/Application/NamespaceExtractor.php

Closes https://github.com/phel-lang/phel-lang/issues/981
- Fix `doc` command on phar command

Fix doc command on phar

---

CHANGELOG.md
src/php/Run/Application/EvalModeExecutor.php
src/php/Run/Infrastructure/Command/ReplCommand.php
src/php/Run/RunFactory.php
tests/php/Integration/Run/Command/Repl/ReplTestCommand.php
tests/php/Integration/Run/Command/Repl/ReplTestIo.php

Closes: https://github.com/phel-lang/phel-lang/issues/991
It would be helpful to run phel code in one command for quick testing and check the output.
- Add `--eval` option to `phel repl` command

Add repl --eval option

---

CHANGELOG.md
src/php/Console/Infrastructure/ConsoleBootstrap.php

When no args are provided, you get the `list` by default
Make `repl` the default command when no args are provided to the executable.
The best solution is to make REPL the default command (which we've done), so you should use:
- `bin/phel` - runs REPL interactively
- `bin/phel repl --eval "(+ 2 3)"` - runs REPL in eval mode
- `bin/phel run --debug local/boot.phel` - runs other commands
You can still see the current version and all available commands with the `list` command:

Set repl as default command instead of help

---

src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/TrySymbol.php
tests/php/Unit/Compiler/Analyzer/SpecialForm/TrySymbolTest.php

https://scrutinizer-ci.com/g/phel-lang/phel-lang/code-structure/main/operation/Phel%5CCompiler%5CDomain%5CAnalyzer%5CTypeAnalyzer%5CSpecialForm%5CTrySymbol::analyze
Refactor TrySymbol for better readability

Refactor TrySymbol for better readability
