.github/workflows/ci.yml, psalm.xml, src/php/Reader.php
Similar as I have in some of my other projects ([EdifactParser](https://github.com/Chemaclass/EdifactParser/blob/master/.github/workflows/ci.yml) for example), or even in the [PHPUnit](https://github.com/sebastianbergmann/phpunit/blob/master/.github/workflows/ci.yml), I introduce a basic workflow with two jobs:
* Type Checker: runs `psalm`
* Tests: runs the tests to the compiler itself and the core library
Note:
I increased the level (from 3 to 4) in the `psalm.errorLevel` because psalm had 9 errors which are out of the scope of this PR. The current level is 4 (when it doesn't complain).
=> GitHub workflow

src/php/Printer.php
* Making the class [strict](https://github.com/Chemaclass/php-best-practices/blob/master/technical-skills/strict-types.md) and [final](https://medium.com/@chemaclass/final-classes-in-php-9174e3e2747e).
* Removing unnecessary `else` statements due to return early.
* It also decreases the indentation of the blocks which helps a lot to follow the logic.
=> Cleaning Printer class

src/php/Emitter.php
* Making the class [strict](https://github.com/Chemaclass/php-best-practices/blob/master/technical-skills/strict-types.md) and [final](https://medium.com/@chemaclass/final-classes-in-php-9174e3e2747e).
* Removing unnecessary `else` statements due to return early.
* It also decreases the indentation of the blocks which helps a lot to follow the logic.
* No logic was altered.
=> Cleaning Emitter class

src/php/Emitter.php
Implement @Chemaclass recommendation in the https://github.com/jenshaase/phel-lang/pull/28#discussion_r437644221 comment about return inline the `require`.
=> #28 Emitter class - Return require inline

editor-support/vscode/README.md
Adds instructions on how to install the plugin on Windows using PowerShell.
=> Updates readme for vs code plugin.

src/php/Runtime.php
- Remove unnecessary imports.
- Rearrange properties & methods (static properties on top always).
- Define more strict exceptions (`\RuntimeException` instead of generic `\Exception`).
- Changes in `findFile()` method.
- Return only one object type (`string`) instead of two (`string` or `bool` if error).
- Replace global `strtr()` by `str_replace()` function (more legiblility).
- Changes in `loadNs()` method:
- [Add `true` flag](https://www.php.net/manual/en/function.in-array.php) in `in_array()` global function.
- Remove one identation level because of `findFile()` return type.
- No logic was altered.
=> Cleaning Runtime class

.github/PULL_REQUEST_TEMPLATE.md
The idea of this PR is to create a _pull request template_ as a prototype in order to set a kind of "agreement" for new PRs.
It is very handy and it is automatically integrated into GitHub.
Take a look and tell me what do you think.
=> Add PR template prototype

doc/content/documentation/namespaces.md
Improves namespace documentation with explanations for `:use` and `:require`, what are the differences between the two, how to set and use aliases, and examples.
- Updates namespace documentation.
---
Hope this is ok. If you want I can omit the part about adding paths?
=> Updates namespace documentation. Fixes #35.

src/php/Analyzer/AnalyzeTuple.php, src/php/Analyzer/TupleSymbol/QuoteSymbol.php, tests/php/Analyzer/TupleSymbol/QuoteSymbolTest.php
The idea is to unit test all symbols but not sure 100% if this is the right approach.
So, I pick the simplest one.
Take a look @jenshaase and give me some feedback. :P
---
I checked you can pass as the first argument to `Tuple` anything and it will work.
In fact, in the code, we are only getting the `$tuple[1]`.
Not sure how much "secure" it is... :thinking:
=> Add test QuoteSymbol class

doc/content/documentation/array-table-and-struct.md, doc/content/documentation/basic-types.md, tests/phel/test/core.phel
Added documentation on sets. Closes #77 
- Fixed some typos in the "Array, Table and Struct" documentation.
- Added sets documentation in "Array, Table and Struct" and renamed it "Array, Table, Struct and Set".
- Updated sets' tests in order to reflect that sets are unsorted according to the new documentation.
=> Sets documentation

tests/php/Analyzer/TupleSymbol/ApplySymbolTest.php, tests/php/Analyzer/TupleSymbol/DefStructSymbolTest.php
- Create `DefStructSymbolTest` class
- Create `ApplySymbolTest` class
=> Test analyzer tuplesymbols

src/php/Analyzer/TupleSymbol/DefSymbol.php, src/php/NodeEnvironment.php, tests/php/Analyzer/TupleSymbol/DefSymbolTest.php, tests/php/IntegrationTest.php
Forbid def inside def
- Added a flag (`$defAllowed`) inside the `NodeEnvironment` to keep track of the `DefSymbol` to know if it was already defined.
=> Def inside of Def should not work

src/php/Analyzer/TupleSymbol/DoSymbol.php, tests/php/Analyzer/TupleSymbol/DoSymbolTest.php
Added some unit tests for the DoSymbol class
- Created `DoSymbolTest`
=> Add DoSymbol unit tests

phel, src/php/Commands/CommandUtils.php, src/php/Commands/RunCommand.php, src/php/Commands/TestCommand.php, src/php/Main.php
Clean up the Main class.
- Move out the entry point logic from the Main class to the entry point script (phel).
=> Move out phel entry point logic

Readme.md, docker-compose.yml
Define the docker-compose latest version.
- I added the latest docker-compose version`3.8` to the `docker-compose.yml` file.
=> Define latest version for docker-compose

src/php/Analyzer/TupleSymbol/IfSymbol.php, tests/php/Unit/Analyzer/TupleSymbol/IfSymbolTest.php
Adding tests to IfSymbol Tuple.
- I refactored a little bit and I created some unit tests for the `Tuple\IfSymbol`
=> Adding tests to IfSymbol Tuple

phel, src/php/Command/CommandFactory.php, src/php/Command/CommandFactoryInterface.php, src/php/Compiler/CompilerFactory.php, src/php/Compiler/CompilerFactoryInterface.php, src/php/Main.php, src/php/Runtime.php, tests/php/Integration/Command/RunCommandTest.php, tests/php/Integration/Command/TestCommandTest.php, tests/php/Integration/IntegrationTest.php
I clean up a bit more of the main entry point and minor improvements as well.
- Clean up the `phel` script and the Main class
- Created CompilerFactoryInterface & CommandFactoryInterface
- Clean up the IntegrationTest logic in order to use the CompilerFactory
=> Refactored Main and IntegrationTest

composer.json, src/php/Printer.php, src/php/Printer/ArrayPrinter.php, src/php/Printer/BooleanPrinter.php, src/php/Printer/KeywordPrinter.php, src/php/Printer/NullPrinter.php, src/php/Printer/NumericalPrinter.php, src/php/Printer/ObjectPrinter.php, src/php/Printer/PhelArrayPrinter.php, src/php/Printer/PrinterInterface.php, src/php/Printer/ResourcePrinter.php, src/php/Printer/SetPrinter.php, src/php/Printer/StringPrinter.php, src/php/Printer/StructPrinter.php, src/php/Printer/SymbolPrinter.php, src/php/Printer/TablePrinter.php, src/php/Printer/TuplePrinter.php
This PR solves the issue https://github.com/jenshaase/phel-lang/issues/129.
The `Printer` class goes from being a "God Class" to an entry point for each type of Print.
- Improve the `Printer` class
- Create `PrinterInterface`
- Create a specific class for each Print type.
=> Refactor Printer

Readme.md
I updated yesterday the `composer.json` file with [a new rule](https://github.com/jenshaase/phel-lang/commit/1dc4c52a0dd31531a3ffefaaf204752830f7a1ef#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R42) but I forgot to update also the `README.md` file.
This commit is to focus on update it, also, improve the last part of the file regarding the Zola documentation.
=> Add csrun in test-all & simplify zola documentation

phel, src/php/PhelFacade.php
Clean up the entry point from phel
- Renamed the `Main` class to `PhelFacade`.
=> Rename Main to PhelFacade

phel, src/php/Command/CommandFacade.php, src/php/Command/CommandFacadeInterface.php, src/php/PhelFacade.php
Introducing the Facade pattern in the Command module
- Created CommandFacade, and injecting it into the PhelFacade.
---
The Facade is the only entry point from a module. It will receive its factory in order to create whatever it needs and perform the actions from its "creations".
🤔 I am thinking about how to improve the current design of the project one step forward by following this pattern in all modules (if possible and if it makes sense). I will work in another branch to try some ideas 💻 🏭
=> Created CommandFacade

doc/content/documentation/api.md, src/phel/core.phel, tests/phel/test/core.phel
- Added `rand-nth`: it returns a random item from xs.
```lisp
(rand-nth @["one" "or" "other"])
``` 
It will get one of these: "one", "or", "other"
=> Implementing rand-nth

src/php/Compiler/Analyzer/Ast/PhpVarNode.php, src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitter.php, tests/php/Unit/Compiler/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitterTest.php
- Refactored the `FnAsClassEmitter` class
- Added unit tests for it
=> Refactor FnAsClassEmitter

src/php/Printer/Printer.php
I found a bug in the Printer when I tried to print a struct. The conditional was asking for `AbstractStruct::class === $printerName`, but that's make no sense. The struct is a child of that AbstractStruct, therefore we should check if it's an `instance of`.
- Fixed the conditional bug for object types.
- Cleanup a bit the `Printer` class
- Fix another minor bug: replace `float` to `double`  
- Reason: For historical reasons "double" is returned in case of a float, and not simply "float" ([source](https://www.php.net/manual/en/function.gettype.php))
=> Fix Printer (object types)

Readme.md
- Added scrutinizer badge to the readme
=> Adding scrutinizer to the readme

src/php/Printer/TypePrinter/StringPrinter.php
Refactoring the `StringPrinter`, maybe there is a better approach to improve this class @Chemaclass. 😄 
- Replace `switch` by `if`s
- Move the `special characters` to an array
- Replace conditions by a method name
=> Refactor StringPrinter class

.github/workflows/ci.yml, .php_cs.dist, composer.json, src/php/Compiler/Parser/ParserNode/AbstractAtomNode.php, src/php/Compiler/Parser/ParserNode/BooleanNode.php, src/php/Compiler/Parser/ParserNode/CommentNode.php, src/php/Compiler/Parser/ParserNode/FileNode.php, src/php/Compiler/Parser/ParserNode/InnerNodeInterface.php, src/php/Compiler/Parser/ParserNode/KeywordNode.php, src/php/Compiler/Parser/ParserNode/ListNode.php, src/php/Compiler/Parser/ParserNode/MetaNode.php, src/php/Compiler/Parser/ParserNode/NewlineNode.php, src/php/Compiler/Parser/ParserNode/NilNode.php, src/php/Compiler/Parser/ParserNode/NodeInterface.php, src/php/Compiler/Parser/ParserNode/NumberNode.php, src/php/Compiler/Parser/ParserNode/QuoteNode.php, src/php/Compiler/Parser/ParserNode/StringNode.php, src/php/Compiler/Parser/ParserNode/SymbolNode.php, src/php/Compiler/Parser/ParserNode/TriviaNodeInterface.php, src/php/Compiler/Parser/ParserNode/WhitespaceNode.php
- Minor clean up for all ParserNodes
- Added `declare_strict_types` phpcs rule
=> Clean up ParserNodes

phel, src/php/Command/CommandFactory.php, src/php/Command/FormatCommand.php, src/php/Formatter/AbstractZipper.php, src/php/Formatter/Formatter.php, src/php/Formatter/FormatterFactory.php, src/php/Formatter/FormatterFactoryInterface.php, src/php/Formatter/FormatterInterface.php, src/php/Formatter/ParseTreeZipper.php, src/php/Formatter/Rules/IndentRule.php, src/php/Formatter/Rules/Indenter/BlockIndenter.php, src/php/Formatter/Rules/Indenter/InnerIndenter.php, src/php/Formatter/Rules/Indenter/LineIndenter.php, src/php/Formatter/Rules/Indenter/ListIndenter.php, src/php/Formatter/Rules/RemoveSurroundingWhitespaceRule.php, src/php/Formatter/Rules/RemoveTrailingWhitespaceRule.php, src/php/Formatter/Rules/UnindentRule.php, tests/php/Integration/Command/RunCommandTest.php, tests/php/Integration/Command/TestCommandTest.php, tests/php/Unit/Formatter/ArrayZipper.php, tests/php/Unit/Formatter/Rules/IndentRuleTest.php, tests/php/Unit/Formatter/Rules/RemoveSurroundingWhitespaceRuleTest.php, tests/php/Unit/Formatter/Rules/RemoveTrailingWhitespaceRuleTest.php, tests/php/Unit/Formatter/Rules/RuleParserTrait.php, tests/php/Unit/Formatter/Rules/UnindentRuleTest.php, tests/php/Unit/Formatter/ZipperTest.php
Following the same architecture as the other modules, I created a factory for the Formatter module.
- Created FormatterFactory
- Some cleanup and minor refactoring to the Formatter unit tests as well
=> Refactoring Formatter module: adding FormatterFactory

doc/content/documentation/getting-started.md
=> fix composer require

src/php/Lang/AbstractType.php, src/php/Lang/IteratorComparatorTrait.php, src/php/Lang/PhelArray.php, src/php/Lang/Set.php, src/php/Lang/Table.php, src/php/Lang/Tuple.php, tests/phel/test/core.phel, tests/phel/test/http.phel, tests/php/Unit/Lang/PhelArrayTest.php
Issue: https://github.com/phel-lang/phel-lang/issues/211
- Add some extra logic to `PhelArray->equals()` in order to be able to compare in more detail the internal data from them.
=> Fix comparing arrays

Changelog.md, doc/content/_index.md, doc/content/documentation/getting-started.md, doc/content/documentation/repl.md, doc/sass/_base.scss
Updated documentation for the first release
- Updated the getting started guide
- Improved Repl docs
- Add Changelog.md
=> Documentation v0.1.0

build/Dockerfile, composer.lock
Update Dockerfile as we did it in the scaffolding (see https://github.com/phel-lang/phel-scaffolding/pull/11)
- Copy the composer binary from the composer image in Dockerfile
- Update composer dev dependencies as well
=> Update composer in Dockerfile

src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/CallEmitter.php, src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/DefStructEmitter.php, src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/IfEmitter.php, src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
- Refactored CallEmitter, DefStructEmitter, IfEmitter & NsEmitter.
=> Refactor some NodeEmitters

src/phel/core/sequence-functions.phel, tests/phel/test/core/sequence-functions.phel
Adding `take-last` phel function
- Added a new phel function `take-last`
=> Adding take-last

.github/workflows/ci.yml
- Changing the CI to use composer install instead of update
=> Using composer install in the CI

doc/content/documentation/api.md, src/phel/core/type-operation.phel
- Minor update on phel `type` function doc
- Updated the `api.md` with `php build-api-page.php > content/documentation/api.md`
=> Update API doc

Changelog.md, doc/content/documentation/api.md, src/phel/core.phel, src/phel/core/regex-functions.phel, tests/phel/test/core/regex-functions.phel
Create a similar function as https://clojuredocs.org/clojure.core/re-seq
- Added `re-seq` phel function inside `/core/regex-functions.phel`
- Updated the `api.md` with `php build-api-page.php > content/documentation/api.md`
=> Adding re-seq phel function

composer.json, composer.lock
- Update to the first stable version of `phpbench` 🥳
=> Update phpbench to 1.0

src/php/Lang/Collections/Map/PersistentArrayMap.php, src/php/Lang/Collections/Map/PersistentHashMap.php, src/php/Lang/Collections/Map/TransientMapWrapper.php, tests/phel/test/core/for-loop.phel
Bug fix for #289 
-  Add a transient map wrapper thats wrap TransientArrayMap and TransientHashMap
=> Fixes #289: Add a transient map wrapper

src/php/Command/CommandConfig.php, src/php/Command/CommandFactory.php
- Move the file paths from Factory to the Config
=> Minor refactor on CommandFactory

composer.json, composer.lock
Recently we created the release [0.3.0](https://github.com/gacela-project/gacela/tree/0.3.0) from `Gacela`.
This PR is to update the dependency to the last version, no extra-changes needed 👍🏼
=> Update Gacela dependency

composer.json, composer.lock, phel, src/php/Command/CommandConfig.php
There are no big changes from Gacela that affect Phel, but minor improvements and additional features that I implemented in Gacela that we might want to benefit from in Phel as well. Therefore I want to update it :) 
- Update Gacela from 0.6 to 0.8. It has some minor improvements.
=> Update Gacela 0.8

src/php/Run/Command/Run/RunCommand.php, src/php/Run/RunFacade.php, src/php/Run/RunFacadeInterface.php, src/php/Run/RunFactory.php, src/php/Run/Runner/NamespaceRunner.php, src/php/Run/Runner/NamespaceRunnerInterface.php
This PR adds an API to run code from a given namespace. This can be used as an entry point for a web server.
=> Added an API run run code from a give namespace

src/php/Compiler/Analyzer/Environment/GlobalEnvironment.php
This PR is addressing this comment https://github.com/phel-lang/phel-lang/pull/385/files#r761722667
- Apply some refactoring to improve the readability for the `GlobalEnvironment` class
=> Refactor GlobalEnvironment

.github/workflows/ci.yml, src/phel/http.phel, src/php/Compiler/Lexer/TokenStream.php, src/php/Lang/Collections/HashSet/TransientHashSet.php, src/php/Lang/Collections/LinkedList/EmptyList.php, src/php/Lang/Collections/LinkedList/PersistentList.php, src/php/Lang/Collections/Map/AbstractPersistentMap.php, src/php/Lang/Collections/Map/ArrayNode.php, src/php/Lang/Collections/Map/ArrayNodeIterator.php, src/php/Lang/Collections/Map/HashCollisionNodeIterator.php, src/php/Lang/Collections/Map/IndexedNode.php, src/php/Lang/Collections/Map/IndexedNodeIterator.php, src/php/Lang/Collections/Map/TransientArrayMap.php, src/php/Lang/Collections/Map/TransientHashMap.php, src/php/Lang/Collections/Map/TransientMapWrapper.php, src/php/Lang/Collections/Struct/AbstractPersistentStruct.php, src/php/Lang/Collections/Vector/AbstractPersistentVector.php, src/php/Lang/Collections/Vector/RangeIterator.php, src/php/Lang/Collections/Vector/TransientVector.php, src/php/Lang/PhelArray.php, src/php/Lang/Set.php, src/php/Lang/Table.php
PHP 8.1 was released a few weeks ago.
Make Phel compatible with PHP 8.1
* Fixed all deprecation warnings
* Enabled PHP 8.1 checks in ci.yml
=> PHP 8.1 support

adrs/php/0002_compiler_module.md, adrs/php/0003_build_module.md, adrs/php/0004_command_module.md, adrs/php/0005_formatter_module.md, adrs/php/0006_interop_module.md, adrs/php/0007_run_module.md, phel-config.php
The project architecture has some level of complexity that might scare new joiners. Even for ourselves, I think it would be good to document somehow a bit what responsibilities do we want to give to each module that we have. 
Define a ADR for each module, and describe what responsibilities do they have. 
- Create a tiny-basic ADR for each module.
> We can improve them in the future, and we should keep them updated. 
> The main goal is to have this as technical-documentation about the project architecture.
> We could use these little "adrs-templates" as a place to add more docs when need it.
=> Adding ADRs for different modules

src/phel/core.phel, tests/phel/test/core/math-operation.phel
The function ensures that a value lies in the specified range. Returns the value v
if it is in the range, or min if v is less than min, or max if v is greater than max.
=> Adds a new function: coerce-in

composer.json, composer.lock, src/php/Build/BuildDependencyProvider.php, src/php/Formatter/FormatterDependencyProvider.php, src/php/Interop/InteropDependencyProvider.php, src/php/Run/RunDependencyProvider.php, tests/php/Integration/Compiler/Reader/ReaderTest.php
- Update gacela to 0.11
- Clean ups the DependencyProviders removing the unnecessary return types from the closures
=> Update gacela version

src/php/Build/Command/CompileCommand.php
The compile command will now show correct error messages if there are errors in the compiled files.
=> Fixes #410 Improve error handling in compile command

src/phel/core.phel, src/phel/html.phel, src/phel/repl.phel, src/phel/test.phel, src/php/Compiler/Analyzer/Environment/GlobalEnvironment.php, tests/php/Integration/Fixtures/Ns/munge-ns.test
As we discuss, the purpose of this PR is to standardise the API documentation.
In order to achieve that, I add a final dot to the symbol documentation.
=> Add final dot to symbol doc

composer.lock, src/php/Lang/AbstractType.php, tests/php/Unit/Compiler/Analyzer/AnalyzeSymbolTest.php
* Run `composer update`
* Fixed test error
* Added missing return type
=> Updated dependencies

composer.json, composer.lock, src/php/Build/Command/CompileCommand.php, src/php/Formatter/Infrastructure/Command/FormatCommand.php, src/php/Run/Command/TestCommand.php
- Update gacela to 0.17
- use `DocBlockResolverAwareTrait` instead of `FacadeResolverAwareTrait`
=> Update gacela 0.17

src/phel/core.phel, src/phel/http.phel, tests/phel/test/core/boolean-operation.phel, tests/phel/test/core/for-loop.phel, tests/phel/test/http.phel
No behaviour changes, just formating `src` and `tests`. 
Running:
```bash
php phel format src tests
```
=> Format src and tests directories

src/phel/core.phel, src/phel/html.phel, src/phel/http.phel, src/phel/repl.phel, src/phel/test.phel
Fix some English typos among the `src/phel/*.phel` files.
=> Improve Phel documentation

composer.json, composer.lock, tests/phel/test/special-forms.phel, tests/php/Integration/Fixtures/PhpObjectSet/set-class-property.test, tests/php/Integration/Run/Command/Repl/ReplCommandTest.php
- Update all dev dependencies
- Rename `stdclass` to `stdClass`
=> Rename stdclass to stdClass

src/php/Build/Infrastructure/Command/CompileCommand.php
- Similar as we currently have on `TestCommand`, add the execution time on `CompileCommand`
https://user-images.githubusercontent.com/5256287/200165245-632a3c8c-d990-4d5e-9f7e-56cb2d9d59a8.mov
=> Add execution time on compile command

src/php/Lang/Hasher.php
I was wondering if we could improve the [Scrutinizer score](https://scrutinizer-ci.com/g/phel-lang/phel-lang/code-structure/master/operation/Phel%5CLang%5CHasher::hash) of this class, by applying some refactoring techniques:
>**Note**: CRAP: Change Risk Anti Pattern (compares the number of tests to the complexity of the method)
Improve readability of the `Phel\Lang\Hasher`
- Refactor Hasher introducing constants for raw-integers and applying extract-method to encapsulate related logic.
=> Refactor Hasher

CHANGELOG.md
Set release 0.9 and date in CHANGELOG.
The Blog entry for the website is also prepared: https://github.com/phel-lang/phel-lang.org/pull/58 
Suggestion for the https://github.com/phel-lang/phel-lang/releases
> 0.9.0 - ApiFacade
> 
> See the [blog post](https://phel-lang.org/blog/release-0-9/) or [Changelog](https://github.com/phel-lang/phel-lang/blob/master/CHANGELOG.md) for more information.
=> Set release 0.9

.github/workflows/ci.yml, composer.json, composer.lock, psalm.xml, src/php/Compiler/Domain/Lexer/TokenStream.php, src/php/Lang/Collections/HashSet/TransientHashSetInterface.php, src/php/Lang/SeqInterface.php, src/php/Lang/TypeInterface.php
- Closes https://github.com/phel-lang/phel-lang/pull/591
- Closes https://github.com/phel-lang/phel-lang/pull/590
- Solve `psalm` conflicts
- Update dependencies
=> Update & fix psalm config + files

CHANGELOG.md, src/phel/repl.phel
Fix for #594 
Updated the namespace of the NodeEnvironment class
=> Fixed the phel\repl\doc function.

.github/CONTRIBUTING.md
Update description from `CONTRIBUTING` file with latest changes, like:
- Use ´main´ as main branch instead of ´master´
- Add `phpstan` among `psalm`
- Update PHP version to `8.0`
- so on...
=> Update CONTRIBUTING.md file

README.md, composer.json
- Upgrade gacela to latest 1.5
This release has a new command that shows the list of modules and gacela classes for each one. For example:
=> Upgrade gacela:1.5

CHANGELOG.md, src/php/Command/Domain/Handler/ExceptionHandler.php, tests/php/Benchmark/Command/CommandBench.php, tests/php/Benchmark/Command/fixtures/run-command.phel
There are many different PHP internal errors that can occur, so we should have a more generic way to display them in our ExceptionHandler
Improve the error output.
Create a custom ErrorHandler for all PHP internal errors.
=> Improve ExceptionHandler

tests/php/Unit/Compiler/Analyzer/SpecialForm/RecurSymbolTest.php
=> Add RecurSymbol unit test

.github/workflows/ci.yml, composer.json, composer.lock, rector.php, src/php/Build/Domain/Compile/DependenciesForNamespace.php, src/php/Command/Domain/Handler/ExceptionHandler.php, src/php/Command/Domain/Shared/Exceptions/TextExceptionPrinter.php, src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DefInterfaceSymbol.php, src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DefStructSymbol.php, src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/TrySymbol.php, src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/MethodEmitter.php, src/php/Compiler/Domain/Reader/QuasiquoteTransformer.php, src/php/Formatter/Domain/Rules/Zipper/AbstractZipper.php, src/php/Lang/Collections/LinkedList/PersistentList.php, src/php/Lang/Collections/Map/ArrayNode.php, src/php/Lang/Collections/Map/IndexedNode.php, src/php/Lang/Collections/Map/PersistentArrayMap.php, src/php/Lang/Collections/Map/TransientArrayMap.php, src/php/Lang/Collections/Struct/AbstractPersistentStruct.php, src/php/Lang/Collections/Vector/AbstractPersistentVector.php, src/php/Printer/TypePrinter/BooleanPrinter.php, src/php/Printer/TypePrinter/StringPrinter.php, tests/php/Unit/Printer/TypePrinter/StringPrinterTest.php
- Add `readonly` to `Printer` and `StringPrinter` classes
- Use individual unit tests instead of dataProvider for `StringPrinterTest`
=> Refactor StringPrinter

.github/CONTRIBUTING.md
Small improvements to `CONTRIBUTING.md` file.
=> Update PHP version & add Rector to CONTRIBUTING.md

.github/workflows/ci.yml, composer.json, composer.lock, psalm.xml, rector.php, src/php/Api/Domain/PhelFnNormalizer.php, src/php/Formatter/Domain/Rules/Zipper/AbstractZipper.php, src/php/Lang/Collections/Vector/AbstractPersistentVector.php
This PR closes: 
- https://github.com/phel-lang/phel-lang/pull/652
- https://github.com/phel-lang/phel-lang/pull/653
- https://github.com/phel-lang/phel-lang/pull/654
- https://github.com/phel-lang/phel-lang/pull/655
- https://github.com/phel-lang/phel-lang/pull/656
- https://github.com/phel-lang/phel-lang/pull/657
=> Update composer & CI dependencies

composer.json, composer.lock, rector.php, src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitter.php, src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/MethodEmitter.php, src/php/Lang/Collections/Map/IndexedNode.php
Upgrade Rector to 1.0.0 + some code changes 🚀
=> Upgrade Rector 1.0.0

composer.lock, src/php/Build/Domain/Extractor/NamespaceExtractor.php
Run `composer update` command to update `phpunit`, `symfony/console` and others.
=> Update composer dependencies

.editorconfig, CHANGELOG.md, src/phel/core.phel, tests/phel/test/core/math-operation.phel, tests/phel/test/core/type-operation.phel
- define indent_size=2 for phel files
- typo in tests math-operation
- allow empty? number,string,collection
=> Add support for numeric on empty?

bin/phel
Fix: https://github.com/NixOS/nixpkgs/pull/314348
Context: https://github.com/phel-lang/phel-lang/commit/9a5dcea39bd99e2b4f06a0b009f2d86f408ee561
=> fix: restore pre-refactor behaviour

.php-cs-fixer.dist.php, tests/php/Integration/Interop/Command/Export/ExportCommandTest.php
=> Flaky ExportCommandTest 

CHANGELOG.md, src/php/Api/Infrastructure/Command/DocCommand.php
Improve the output for the doc command
- Display "doc" command as table
=> Improve output for doc command

CHANGELOG.md, src/php/Compiler/Application/Analyzer.php, src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php, src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironmentInterface.php, tests/phel/test/core/control-structures.phel
Closes: https://github.com/phel-lang/phel-lang/issues/723
Original idea by @smeghead https://github.com/phel-lang/phel-lang/pull/724#issuecomment-2181921658 
Allow using expressions inside `case`
- Instead of using a bool, use a counter to allow using nested private access on macros
=> Fix recursive private access

.php-cs-fixer.dist.php, composer.json, composer.lock, tests/php/Unit/Lang/Collections/LinkedList/EmptyListTest.php, tests/php/Unit/Lang/Collections/LinkedList/PersistentListTest.php, tests/php/Unit/Lang/Collections/Map/ArrayNodeTest.php, tests/php/Unit/Lang/Collections/Map/PersistentArrayMapTest.php, tests/php/Unit/Lang/Collections/Map/PersistentHashMapTest.php, tests/php/Unit/Lang/Collections/Map/TransientArrayMapTest.php, tests/php/Unit/Lang/Collections/Map/TransientHashMapTest.php, tests/php/Unit/Lang/Collections/Vector/PersistentVectorTest.php, tests/php/Unit/Lang/Collections/Vector/TransientVectorTest.php
- Update dependencies
- Run rector
- Run cs-fixer in parallel
=> Update dependencies & run rector

composer.json, composer.lock, src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php, src/php/Interop/PhelCallerTrait.php, tests/php/Integration/Run/Command/Repl/ReplCommandTest.php
Install and run ergebnis/composer-normalize by @localheinz
=> Install and run composer-normalize

src/php/Api/ApiFactory.php, src/php/Api/Application/PhelFnNormalizer.php, src/php/Api/Domain/PhelFnLoaderInterface.php, src/php/Api/Infrastructure/PhelFnLoader.php, tests/php/Integration/Api/ApiFacadeTest.php, tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php
Closes: #763
Add native phel symbols to API documentation
- Add manually the documentation for PRIVATE_SYMBOLS which are functions that does not exists on phel code
=> Add native phel symbols to api facade

composer.json, composer.lock, rector.php, src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/Binding/Deconstructor/BindingDeconstructorInterface.php, src/php/Compiler/Domain/Parser/ParserNode/AbstractAtomNode.php, src/php/Formatter/Domain/Rules/Zipper/AbstractZipper.php, src/php/Lang/Collections/HashSet/PersistentHashSet.php, src/php/Lang/Collections/HashSet/PersistentHashSetInterface.php, src/php/Lang/Collections/HashSet/TransientHashSetInterface.php, src/php/Lang/Collections/LinkedList/PersistentList.php, src/php/Lang/Collections/LinkedList/PersistentListInterface.php, src/php/Lang/Collections/Map/AbstractPersistentMap.php, src/php/Lang/Collections/Map/HashCollisionNode.php, src/php/Lang/Collections/Map/HashMapNodeInterface.php, src/php/Lang/Collections/Map/IndexedNode.php, src/php/Lang/Collections/Map/PersistentArrayMap.php, src/php/Lang/Collections/Map/PersistentMapInterface.php, src/php/Lang/Collections/Map/TransientArrayMap.php, src/php/Lang/Collections/Map/TransientHashMap.php, src/php/Lang/Collections/Map/TransientMapInterface.php, src/php/Lang/Collections/Map/TransientMapWrapper.php, src/php/Lang/Collections/Vector/PersistentVector.php, src/php/Lang/Collections/Vector/PersistentVectorInterface.php, src/php/Lang/Collections/Vector/RangeIterator.php, src/php/Lang/Collections/Vector/TransientVector.php, src/php/Lang/Collections/Vector/TransientVectorInterface.php, src/php/Lang/ContainsInterface.php, src/php/Lang/Variable.php, tests/php/Benchmark/Lang/Collections/Vector/SimpleImmutableVectorBench.php
- Update all dependencies
- Especially PHPSTan `2.0` and Rector `2.0-rc`
- Apply rector fixes
=> Update rector and apply fixes

CHANGELOG.md, phpstan.neon, src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/ReadModel/FnSymbolTuple.php, src/php/Compiler/Domain/Parser/ParserNode/TriviaNodeInterface.php, src/php/Formatter/Domain/Rules/IndentRule.php, src/php/Formatter/Domain/Rules/Zipper/AbstractZipper.php, src/php/Formatter/Domain/Rules/Zipper/ParseTreeZipper.php, src/php/Lang/AbstractType.php, src/php/Lang/Collections/LinkedList/EmptyList.php, src/php/Lang/Collections/LinkedList/PersistentListInterface.php, src/php/Lang/Collections/Map/Box.php, src/php/Lang/Collections/Map/HashCollisionNodeIterator.php, src/php/Lang/Collections/Map/HashMapNodeInterface.php, src/php/Lang/Collections/Map/IndexedNode.php, src/php/Lang/Collections/Vector/PersistentVectorInterface.php, src/php/Lang/Collections/Vector/TransientVectorInterface.php, src/php/Printer/Printer.php, tests/php/Unit/Formatter/Domain/Rules/Zipper/ArrayZipper.php
We were using the lowest PHPStan level (1) until today. 
The aim is to increase its level to improve the internal code quality of the project.
Apply refactoring suggested by PHPStan level 2
Update also some psalm complains after doing those changes from PHPStan. They play very well along :)
=> Use PHPStan level 2

CHANGELOG.md, src/phel/repl.phel, src/php/Printer/Printer.php, src/php/Run/RunFactory.php, tests/php/Integration/Printer/PrinterTest.php
Closes: https://github.com/phel-lang/phel-lang/issues/788
=> Strings in output should be wrapped with quotes

src/php/Lang/Collections/Vector/RangeIterator.php
- reduce overhead in RangeIterator
=> Optimize vector iteration

CHANGELOG.md, src/phel/core.phel, tests/phel/test/core/macroexpand.phel, tests/php/Integration/Api/ApiFacadeTest.php
- implement `macroexpand-1` and `macroexpand` in core
- test new macroexpansion helpers
- update API integration test count
- `composer test-core`
- `composer test-all`
=> Add macroexpand functions

CHANGELOG.md, src/php/Run/Domain/Repl/ReplCommandSystemIo.php
The tab key does not do anything when writing a word on the REPL
Display help with current functions available from REPL
=> Add REPL completion

CHANGELOG.md, src/php/Lang/Collections/Vector/PersistentVector.php, src/php/Lang/Collections/Vector/TransientVector.php
- cache tail size in `PersistentVector` and `TransientVector`
- update tail size when modifying transient vectors
=> Improve vector performance

CHANGELOG.md, src/phel/str.phel, tests/phel/test/str.phel, tests/php/Integration/Api/ApiFacadeTest.php
Add pad-left and pad-right functions
=> Add pad-left and pad-right functions

CHANGELOG.md, src/phel/trace.phel, tests/phel/test/trace.phel
Inspired by https://stackoverflow.com/a/2352491/3454593
- Add `phel\trace\dotrace` function
=> Add dotrace function

CHANGELOG.md, src/phel/trace.phel, tests/phel/test/trace.phel
- Add `trace/dbg`
- Add `reset-trace-state!`
=> Add dbg function

CHANGELOG.md, src/php/Build/Application/FileCompiler.php
Looking for optimizations opportunitites.
Run native `opcache_compile_file` on `FileCompiler` (being used on `phel build`)
=> Enable opcache on file compilation

CHANGELOG.md, src/php/Compiler/Domain/Evaluator/RequireEvaluator.php, src/php/Run/Infrastructure/Command/RunCommand.php
Follow up after: https://github.com/phel-lang/phel-lang/pull/842
=> Add --clear-opcache option to phel run

CHANGELOG.md, src/php/Console/ConsoleProvider.php, src/php/Run/Infrastructure/Command/DoctorCommand.php, tests/php/Integration/Run/Command/Doctor/DoctorCommandTest.php
This is especially useful when using the PHAR executable, to make sure if you can run it or not.
- Create a new command `phel doctor`
=> Add doctor command

.gitignore, CHANGELOG.md, build/build-phar.php, build/phar.sh, src/php/Build/Application/NamespaceExtractor.php, src/php/Command/Application/DirectoryFinder.php, src/php/Phel.php, src/php/Run/Application/NamespacesLoader.php, tests/php/Unit/Command/Application/DirectoryFinderTest.php
- Fix the PHAR loading the core functions
=> Fix load core ns from PHAR

CHANGELOG.md, src/phel/core.phel, tests/phel/test/core/sequence-functions.phel, tests/php/Integration/Api/ApiFacadeTest.php
=> Add function unset-in

CHANGELOG.md, src/phel/base64.phel, src/php/Api/ApiConfig.php, tests/phel/test/base64.phel, tests/php/Integration/Api/ApiFacadeTest.php
- Add base64 functions
- `base64/encode`
- `base64/decode`
- `base64/encode-url`
- `base64/decode-url`
=> Add base64 functions

CHANGELOG.md, src/php/Build/Domain/Extractor/TopologicalNamespaceSorter.php, tests/php/Unit/Build/Domain/Extractor/TopologicalNamespaceSorterTest.php
Optimized the topological sorting algorithm by replacing repeated linear searches with constant-time set lookups to avoid circular dependency checks and improve runtime performance
=>  Improve TopologicalNamespaceSorter performance

CHANGELOG.md, src/php/Build/Application/DependenciesForNamespace.php, src/php/Build/Application/NamespaceExtractor.php, src/php/Build/Domain/Extractor/NamespaceExtractorInterface.php, tests/php/Unit/Build/Domain/Extractor/NamespaceExtractorTest.php
- Improve performance
- `DependenciesForNamespace`
- `NamespaceExtractor`
=> Refactor NamespaceExtractor and DependenciesForNamespace

CHANGELOG.md, src/php/Build/Application/DependenciesForNamespace.php, src/php/Build/Domain/Extractor/NamespaceExtractorInterface.php
Fixes: https://github.com/phel-lang/phel-lang/issues/861 by @jasalt 
Revert 9e6901e62f6ed7cb1ff97ab20f91de138d83f397
=> Fix require broke in repl

tests/php/Unit/Compiler/Analyzer/SpecialForm/ThrowSymbolTest.php
Closes https://github.com/phel-lang/phel-lang/issues/480
=> Test ThrowSymbol

.github/RELEASE.md, CHANGELOG.md, bin/phel, src/php/Console/Application/VersionFinder.php, src/php/Console/ConsoleFacade.php, src/php/Console/ConsoleFacadeInterface.php, src/php/Console/ConsoleFactory.php, src/php/Console/ConsoleProvider.php, src/php/Run/Infrastructure/Command/ReplCommand.php, src/php/Run/RunFacade.php, src/php/Run/RunFacadeInterface.php, src/php/Run/RunFactory.php, src/php/Run/RunProvider.php, tests/php/Unit/Console/Application/VersionFinderTest.php
=> Show current phel repl version

src/php/Api/Application/PhelFnNormalizer.php, src/php/Api/Domain/PhelFnLoaderInterface.php, src/php/Api/Infrastructure/Command/DocCommand.php, src/php/Api/Infrastructure/PhelFnLoader.php, src/php/Api/Transfer/PhelFunction.php, tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php
Related https://github.com/phel-lang/phel-lang.org/issues/134
Add new fields to `PhelFunction` DTO
=> Add docUrl and fnNs to PhelFunction

CHANGELOG.md, src/phel/core.phel, tests/phel/test/core/sequence-functions.phel, tests/php/Integration/Api/ApiFacadeTest.php
Closes: https://github.com/phel-lang/phel-lang/issues/955 by @jasalt
=> Add "into" core function

CHANGELOG.md, phpstan.neon, src/Phel.php, src/php/Api/Application/PhelFnNormalizer.php, src/php/Api/Application/ReplCompleter.php, src/php/Api/Domain/PhelFnLoaderInterface.php, src/php/Api/Infrastructure/PhelFnLoader.php, src/php/Command/Application/TextExceptionPrinter.php, src/php/Command/Domain/Exceptions/Extractor/FilePositionExtractor.php, src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/ReadModel/FnSymbolTuple.php, src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/RecurEmitter.php, src/php/Compiler/Domain/Reader/ExpressionReader/ListFnReader.php, src/php/Filesystem/Application/TempDirFinder.php, src/php/Formatter/Domain/Rules/Zipper/AbstractZipper.php, src/php/Interop/PhelCaller.php, src/php/Lang/Generators.php, src/php/Lang/Keyword.php, src/php/Run/Infrastructure/Command/DoctorCommand.php
Increasing @phpstan level will help improving code quality 
Increase PHPStan level from 3 to 4
=> Increase PHPStan level to 4

CHANGELOG.md, phpstan.neon, src/Phel.php, src/php/Build/Application/NamespaceExtractor.php, src/php/Formatter/Domain/Rules/RemoveSurroundingWhitespaceRule.php, src/php/Formatter/Domain/Rules/RemoveTrailingWhitespaceRule.php, src/php/Formatter/Domain/Rules/UnindentRule.php
Increasing @phpstan level will help improving code quality 
Increase PHPStan level from 4 to 5
=> Increase PHPStan level to 5
